//go:build profilegen
// +build profilegen

// profilegen - 浏览器指纹配置代码生成工具
//
// 该工具从 YAML 配置文件生成类型安全的 Go 代码，消除 nolint:composites 警告。
//
// 使用方式:
//
//	go run ./cmd/profilegen -input profiles/specs -output profiles/generated.go
//
// 配置文件格式见: profiles/specs/chrome_133.yaml
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"time"
)

const generatedCodeTemplate = `// Code generated by cmd/profilegen; DO NOT EDIT.
// Generated at: {{ .Timestamp }}
// Source files: {{ .SourceFiles }}

package profiles

import (
	"github.com/bogdanfinn/fhttp/http2"
	tls "github.com/bogdanfinn/utls"
)

func init() {
	// 注册所有生成的指纹配置
	{{- range .Profiles }}
	registerGeneratedProfile("{{ .Name }}", {{ .VarName }})
	{{- end }}
}

{{ range .Profiles }}
// {{ .VarName }} 是 {{ .DisplayName }} 的指纹配置（代码生成）
var {{ .VarName }} = ClientProfile{
	clientHelloId: tls.ClientHelloID{
		Client:               "{{ .Client }}",
		RandomExtensionOrder: {{ .RandomExtensionOrder }},
		Version:              "{{ .Version }}",
		Seed:                 nil,
		SpecFactory:          {{ .VarName }}SpecFactory,
	},
	settings: map[http2.SettingID]uint32{
		{{- range $key, $value := .Settings }}
		http2.{{ $key }}: {{ $value }},
		{{- end }}
	},
	settingsOrder: []http2.SettingID{
		{{- range .SettingsOrder }}
		http2.{{ . }},
		{{- end }}
	},
	pseudoHeaderOrder: []string{
		{{- range .PseudoHeaderOrder }}
		"{{ . }}",
		{{- end }}
	},
	connectionFlow: {{ .ConnectionFlow }},
	{{- if .HeaderPriority }}
	headerPriority: &http2.PriorityParam{
		StreamDep: {{ .HeaderPriority.StreamDep }},
		Exclusive: {{ .HeaderPriority.Exclusive }},
		Weight:    {{ .HeaderPriority.Weight }},
	},
	{{- end }}
	{{- if .Priorities }}
	priorities: []http2.Priority{
		{{- range .Priorities }}
		{
			StreamID: {{ .StreamID }},
			PriorityParam: http2.PriorityParam{
				StreamDep: {{ .StreamDep }},
				Exclusive: {{ .Exclusive }},
				Weight:    {{ .Weight }},
			},
		},
		{{- end }}
	},
	{{- end }}
}

// {{ .VarName }}SpecFactory 创建 {{ .DisplayName }} 的 TLS ClientHello 规范
func {{ .VarName }}SpecFactory() (tls.ClientHelloSpec, error) {
	return tls.ClientHelloSpec{
		CipherSuites: []uint16{
			{{- range .CipherSuites }}
			{{ . }},
			{{- end }}
		},
		CompressionMethods: []byte{
			{{- range .CompressionMethods }}
			{{ . }},
			{{- end }}
		},
		Extensions: []tls.TLSExtension{
			{{- range .Extensions }}
			{{ . }},
			{{- end }}
		},
	}, nil
}
{{ end }}
`

// ProfileSpec 定义单个指纹配置
type ProfileSpec struct {
	Name                 string
	VarName              string
	DisplayName          string
	Client               string
	Version              string
	RandomExtensionOrder bool
	CipherSuites         []string
	CompressionMethods   []string
	Extensions           []string
	Settings             map[string]uint32
	SettingsOrder        []string
	PseudoHeaderOrder    []string
	ConnectionFlow       uint32
	HeaderPriority       *PriorityParam
	Priorities           []Priority
}

type PriorityParam struct {
	StreamDep uint32
	Exclusive bool
	Weight    uint8
}

type Priority struct {
	StreamID uint32
	PriorityParam
}

// TemplateData 传递给模板的总数据
type TemplateData struct {
	Timestamp   string
	SourceFiles string
	Profiles    []ProfileSpec
}

func main() {
	var (
		inputDir   = flag.String("input", "profiles/specs", "输入配置文件目录")
		outputFile = flag.String("output", "profiles/generated.go", "输出 Go 文件路径")
	)
	flag.Parse()

	// 确保输入目录存在
	if _, err := os.Stat(*inputDir); os.IsNotExist(err) {
		fmt.Fprintf(os.Stderr, "错误: 输入目录不存在: %s\n", *inputDir)
		os.Exit(1)
	}

	// 解析所有 YAML 文件
	profiles, files, err := parseAllProfiles(*inputDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "错误: 解析配置文件失败: %v\n", err)
		os.Exit(1)
	}

	if len(profiles) == 0 {
		fmt.Fprintf(os.Stderr, "警告: 未找到任何 YAML 配置文件\n")
		os.Exit(1)
	}

	// 准备模板数据
	data := TemplateData{
		Timestamp:   time.Now().Format(time.RFC3339),
		SourceFiles: strings.Join(files, ", "),
		Profiles:    profiles,
	}

	// 生成代码
	if err := generateCode(data, *outputFile); err != nil {
		fmt.Fprintf(os.Stderr, "错误: 生成代码失败: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("✓ 成功生成 %d 个指纹配置到 %s\n", len(profiles), *outputFile)
	fmt.Printf("✓ 源文件: %s\n", strings.Join(files, ", "))
}

// generateCode 使用模板生成 Go 代码
func generateCode(data TemplateData, outputPath string) error {
	tmpl, err := template.New("profiles").Parse(generatedCodeTemplate)
	if err != nil {
		return fmt.Errorf("解析模板失败: %w", err)
	}

	// 创建输出目录
	dir := filepath.Dir(outputPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("创建目录失败: %w", err)
	}

	// 创建输出文件
	file, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("创建文件失败: %w", err)
	}
	defer file.Close()

	// 执行模板
	if err := tmpl.Execute(file, data); err != nil {
		return fmt.Errorf("执行模板失败: %w", err)
	}

	return nil
}
