//go:build profilegen
// +build profilegen

// profilegen - browser fingerprint configuration code generation tool
//
// This tool generates type-safe Go code from YAML configuration files, eliminating nolint:composites warnings.
//
// Usage:
//
//	go run ./cmd/profilegen -input profiles/specs -output profiles/generated.go
//
// Configuration file format see: profiles/specs/chrome_133.yaml
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	"gopkg.in/yaml.v3"
)

const generatedCodeTemplate = `// Code generated by cmd/profilegen; DO NOT EDIT.
// Generated at: {{ .Timestamp }}
// Source files: {{ .SourceFiles }}

package profiles

import (
	"github.com/bogdanfinn/fhttp/http2"
	tls "github.com/bogdanfinn/utls"
)

func init() {
	// register all generated fingerprint configurations
	{{- range .Profiles }}
	registerGeneratedProfile("{{ .Name }}", {{ .VarName }})
	{{- end }}
}

{{ range .Profiles }}
// {{ .VarName }} is the fingerprint configuration for {{ .DisplayName }} (code generated)
var {{ .VarName }} = ClientProfile{
	clientHelloId: tls.ClientHelloID{
		Client:               "{{ .Client }}",
		RandomExtensionOrder: {{ .RandomExtensionOrder }},
		Version:              "{{ .Version }}",
		Seed:                 nil,
		SpecFactory:          {{ .VarName }}SpecFactory,
	},
	settings: map[http2.SettingID]uint32{
		{{- range $key, $value := .Settings }}
		http2.{{ $key }}: {{ $value }},
		{{- end }}
	},
	settingsOrder: []http2.SettingID{
		{{- range .SettingsOrder }}
		http2.{{ . }},
		{{- end }}
	},
	pseudoHeaderOrder: []string{
		{{- range .PseudoHeaderOrder }}
		"{{ . }}",
		{{- end }}
	},
	connectionFlow: {{ .ConnectionFlow }},
	{{- if .HeaderPriority }}
	headerPriority: &http2.PriorityParam{
		StreamDep: {{ .HeaderPriority.StreamDep }},
		Exclusive: {{ .HeaderPriority.Exclusive }},
		Weight:    {{ .HeaderPriority.Weight }},
	},
	{{- end }}
	{{- if .Priorities }}
	priorities: []http2.Priority{
		{{- range .Priorities }}
		{
			StreamID: {{ .StreamID }},
			PriorityParam: http2.PriorityParam{
				StreamDep: {{ .StreamDep }},
				Exclusive: {{ .Exclusive }},
				Weight:    {{ .Weight }},
			},
		},
		{{- end }}
	},
	{{- end }}
}

// {{ .VarName }}SpecFactory creates TLS ClientHello specification for {{ .DisplayName }}
func {{ .VarName }}SpecFactory() (tls.ClientHelloSpec, error) {
	return tls.ClientHelloSpec{
		CipherSuites: []uint16{
			{{- range .CipherSuites }}
			{{ . }},
			{{- end }}
		},
		CompressionMethods: []byte{
			{{- range .CompressionMethods }}
			{{ . }},
			{{- end }}
		},
		Extensions: []tls.TLSExtension{
			{{- range .Extensions }}
			{{ . }},
			{{- end }}
		},
	}, nil
}
{{ end }}
`

// ProfileSpec defines a single fingerprint configuration
type ProfileSpec struct {
	Name                 string
	VarName              string
	DisplayName          string
	Client               string
	Version              string
	RandomExtensionOrder bool
	CipherSuites         []string
	CompressionMethods   []string
	Extensions           []string
	Settings             map[string]uint32
	SettingsOrder        []string
	PseudoHeaderOrder    []string
	ConnectionFlow       uint32
	HeaderPriority       *PriorityParam
	Priorities           []Priority
}

type PriorityParam struct {
	StreamDep uint32
	Exclusive bool
	Weight    uint8
}

type Priority struct {
	StreamID uint32
	PriorityParam
}

// TemplateData contains all data passed to template
type TemplateData struct {
	Timestamp   string
	SourceFiles string
	Profiles    []ProfileSpec
}

func main() {
	var (
		inputDir   = flag.String("input", "profiles/specs", "input configuration file directory")
		outputFile = flag.String("output", "profiles/generated.go", "output Go file path")
	)
	flag.Parse()

	// ensure input directory exists
	if _, err := os.Stat(*inputDir); os.IsNotExist(err) {
		fmt.Fprintf(os.Stderr, "error: input directory does not exist: %s\n", *inputDir)
		os.Exit(1)
	}

	// parse all YAML files
	profiles, files, err := parseAllProfiles(*inputDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: failed to parse configuration files: %v\n", err)
		os.Exit(1)
	}

	if len(profiles) == 0 {
		fmt.Fprintf(os.Stderr, "warning: no YAML configuration files found\n")
		os.Exit(1)
	}

	// prepare template data
	data := TemplateData{
		Timestamp:   time.Now().Format(time.RFC3339),
		SourceFiles: strings.Join(files, ", "),
		Profiles:    profiles,
	}

	// generate code
	if err := generateCode(data, *outputFile); err != nil {
		fmt.Fprintf(os.Stderr, "error: failed to generate code: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("✓ successfully generated %d fingerprint configurations to %s\n", len(profiles), *outputFile)
	fmt.Printf("✓ source files: %s\n", strings.Join(files, ", "))
}

// parseAllProfiles parses all YAML configuration files from specified directory
func parseAllProfiles(inputDir string) ([]ProfileSpec, []string, error) {
	var profiles []ProfileSpec
	var files []string

	entries, err := os.ReadDir(inputDir)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to read directory: %w", err)
	}

	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}

		if !strings.HasSuffix(entry.Name(), ".yaml") && !strings.HasSuffix(entry.Name(), ".yml") {
			continue
		}

		filePath := filepath.Join(inputDir, entry.Name())
		content, err := os.ReadFile(filePath)
		if err != nil {
			return nil, nil, fmt.Errorf("failed to read file %s: %w", filePath, err)
		}

		var spec ProfileSpec
		if err := yaml.Unmarshal(content, &spec); err != nil {
			return nil, nil, fmt.Errorf("parse YAML filefailed %s: %w", filePath, err)
		}

		// generate variable name (convert file name to camelCase)
		spec.VarName = strings.TrimSuffix(entry.Name(), filepath.Ext(entry.Name()))

		profiles = append(profiles, spec)
		files = append(files, entry.Name())
	}

	return profiles, files, nil
}

// generateCode generates Go code using template
func generateCode(data TemplateData, outputPath string) error {
	tmpl, err := template.New("profiles").Parse(generatedCodeTemplate)
	if err != nil {
		return fmt.Errorf("parsetemplatefailed: %w", err)
	}

	// create output directory
	dir := filepath.Dir(outputPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create directory: %w", err)
	}

	// create output file
	file, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("createfilefailed: %w", err)
	}
	defer file.Close()

	// executetemplate
	if err := tmpl.Execute(file, data); err != nil {
		return fmt.Errorf("executetemplatefailed: %w", err)
	}

	return nil
}
