package main

import (
	"fmt"
	"os"
	"time"
)

func collectBotFingerprints() []CollectedFingerprint {
	fps := make([]CollectedFingerprint, 0, len(botFingerprintEntries))
	for _, b := range botFingerprintEntries {
		fp := CollectedFingerprint{
			Source:      "bot_knowledge",
			CollectedAt: time.Now().UTC().Format(time.RFC3339),
			BrowserName: b.Name,
			UserAgent:   b.UA,
			JA3Hash:     b.JA3,
			TLS: &TLSFingerprint{
				Version:         0x0303,
				CipherSuites:    b.Ciphers,
				Extensions:      b.Extensions,
				SupportedGroups: b.Curves,
				SNI:             true,
			},
			Metadata: map[string]any{
				"tool":  b.Tool,
				"notes": b.Notes,
			},
		}
		fps = append(fps, fp)
	}
	return fps
}

// collectInternationalBrowsers returns fingerprints for browsers popular outside Western markets.
func collectInternationalBrowsers() []CollectedFingerprint {
	fps := make([]CollectedFingerprint, 0, len(internationalBrowserEntries))
	for _, b := range internationalBrowserEntries {
		fp := CollectedFingerprint{
			Source:      "intl_knowledge",
			CollectedAt: time.Now().UTC().Format(time.RFC3339),
			BrowserName: b.Browser,
			BrowserVer:  b.Version,
			OSName:      b.OS,
			Platform:    "desktop",
			UserAgent:   b.UA,
			TLS: &TLSFingerprint{
				Version:         0x0303,
				CipherSuites:    b.Ciphers,
				Extensions:      b.Extensions,
				SupportedGroups: b.Curves,
				SNI:             true,
			},
			HTTP2: &HTTP2Fingerprint{
				HeaderTableSize:      65536,
				InitialWindowSize:    b.H2Window,
				MaxConcurrentStreams: b.H2Streams,
				MaxFrameSize:         16384,
				PseudoHeaderOrder:    []string{":method", ":authority", ":scheme", ":path"},
				ConnectionFlow:       15663105,
			},
			Metadata: map[string]any{"region": b.Region},
		}
		if b.OS == "Android" || b.OS == "iOS" {
			fp.Platform = "mobile"
		}
		fps = append(fps, fp)
	}
	return fps
}

// generateGoProfiles generates Go code from collected fingerprints.
func generateGoProfiles(result *CollectionResult, outPath string) error {
	f, err := os.Create(outPath)
	if err != nil {
		return err
	}
	defer f.Close()

	fmt.Fprintf(f, "// Code generated by collector. DO NOT EDIT.\n")
	fmt.Fprintf(f, "// Source: %d fingerprints from %v\n", result.TotalCount, result.Sources)
	fmt.Fprintf(f, "// Generated: %s\n\n", result.CollectedAt)
	fmt.Fprintf(f, "package collected\n\n")
	fmt.Fprintf(f, "// CollectedFP represents a collected fingerprint for training.\n")
	fmt.Fprintf(f, "type CollectedFP struct {\n")
	fmt.Fprintf(f, "\tName       string\n")
	fmt.Fprintf(f, "\tBrowser    string\n")
	fmt.Fprintf(f, "\tVersion    string\n")
	fmt.Fprintf(f, "\tOS         string\n")
	fmt.Fprintf(f, "\tCipherSuites []uint16\n")
	fmt.Fprintf(f, "\tExtensions   []uint16\n")
	fmt.Fprintf(f, "\tCurves       []uint16\n")
	fmt.Fprintf(f, "\tUA         string\n")
	fmt.Fprintf(f, "\tJA3Hash    string\n")
	fmt.Fprintf(f, "\tSource     string\n")
	fmt.Fprintf(f, "}\n\n")
	fmt.Fprintf(f, "// AllFingerprints contains all collected fingerprints.\n")
	fmt.Fprintf(f, "var AllFingerprints = []CollectedFP{\n")

	for _, fp := range result.Fingerprints {
		fmt.Fprintf(f, "\t{\n")
		fmt.Fprintf(f, "\t\tName: %q, Browser: %q, Version: %q, OS: %q,\n",
			fp.BrowserName, fp.BrowserName, fp.BrowserVer, fp.OSName)
		if fp.TLS != nil && len(fp.TLS.CipherSuites) > 0 {
			fmt.Fprintf(f, "\t\tCipherSuites: []uint16{")
			for i, c := range fp.TLS.CipherSuites {
				if i > 0 {
					fmt.Fprintf(f, ", ")
				}
				fmt.Fprintf(f, "0x%04x", c)
			}
			fmt.Fprintf(f, "},\n")
		}
		if fp.UserAgent != "" {
			fmt.Fprintf(f, "\t\tUA: %q,\n", fp.UserAgent)
		}
		if fp.JA3Hash != "" {
			fmt.Fprintf(f, "\t\tJA3Hash: %q,\n", fp.JA3Hash)
		}
		fmt.Fprintf(f, "\t\tSource: %q,\n", fp.Source)
		fmt.Fprintf(f, "\t},\n")
	}

	fmt.Fprintf(f, "}\n")
	return nil
}
