// Package ml — pipeline.go provides end-to-end model inference and training pipelines.
//
// ┌─────────────────────────────────────────────────────────────────────┐
// │                  ModelPipeline — Inference Orchestration             │
// │                                                                     │
// │  Raw request                                                        │
// │    ↓ EncodeFingerprint()                                            │
// │  30-dim feature vector                                              │
// │    ↓ FingerprintEncoder.EncodeSingle()                              │
// │  32-dim embedding                                                   │
// │    ├→ BrowserClassifier.ClassifySingle()  → browser identification │
// │    │                                                                │
// │    │  30-dim features + 10-dim cross-layer features                 │
// │    ├→ ForgeryDetector.DetectSingle()      → forgery detection      │
// │    │                                                                │
// │    │  32-dim embedding + forgery result + 8-dim behavior features   │
// │    └→ ThreatAssessor.AssessSingle()       → threat + action        │
// │                                                                     │
// │  All model results aggregated into PipelineResult                   │
// └─────────────────────────────────────────────────────────────────────┘
//
// ┌─────────────────────────────────────────────────────────────────────┐
// │                  Trainer — Training Pipeline                        │
// │                                                                     │
// │  207 browser profiles → data augmentation → training samples        │
// │                                                                     │
// │  Phase 1: Encoder pre-training (triplet loss)                       │
// │    - Positive pairs: same browser + Gaussian noise                  │
// │    - Negative samples: different browser family                     │
// │                                                                     │
// │  Phase 2: Classifier training (cross-entropy)                       │
// │    - Freeze encoder, train classification head                      │
// │                                                                     │
// │  Phase 3: Forgery detector training (binary cross-entropy)          │
// │    - Real samples: from profiles                                    │
// │    - Forged samples: cross-browser layer mixing, headless features  │
// │                                                                     │
// │  Phase 4: Threat assessor training (cross-entropy)                  │
// │    - Initial labels: generated by rule engine                       │
// │    - Ongoing: online feedback fine-tuning                           │
// └─────────────────────────────────────────────────────────────────────┘
package ml

import (
	"sync"

	"github.com/vistone/fingerprint/modules/core"
	"github.com/vistone/fingerprint/modules/profiles"
)

// =========================================================================
// PipelineResult — inference pipeline output
// =========================================================================

// PipelineResult aggregates inference results from all models.
type PipelineResult struct {
	// Fingerprint embedding (32-dim)
	Embedding []float64

	// Browser identification result
	Browser BrowserPrediction

	// Forgery detection result
	Forgery ForgeryResult

	// Threat assessment result
	Threat ThreatPrediction

	// Raw features (for debugging/explainability)
	RawFeatures   []float64
	CrossFeatures []float64
}

// ModelPipeline is the end-to-end inference pipeline chaining four models.
type ModelPipeline struct {
	encoder    *FingerprintEncoder
	classifier *BrowserClassifier
	detector   *ForgeryDetector
	assessor   *ThreatAssessor
	trained    bool
	mu         sync.RWMutex
}

// Trained returns whether the pipeline has been trained or has loaded weights.
func (p *ModelPipeline) Trained() bool {
	p.mu.RLock()
	defer p.mu.RUnlock()
	return p.trained
}

// NewModelPipeline creates a new inference pipeline.
func NewModelPipeline() *ModelPipeline {
	return &ModelPipeline{
		encoder:    NewFingerprintEncoder(),
		classifier: NewBrowserClassifier(),
		detector:   NewForgeryDetector(),
		assessor:   NewThreatAssessor(),
	}
}

// Infer executes the full inference chain from a ClientProfile.
func (p *ModelPipeline) Infer(profile *profiles.ClientProfile, behavior []float64) *PipelineResult {
	p.mu.RLock()
	defer p.mu.RUnlock()

	// 1. Feature encoding
	features := EncodeFingerprint(profile)
	crossFeatures := ComputeCrossLayerFeatures(features)

	// 2. Fingerprint embedding
	embedding := p.encoder.EncodeSingle(features)

	// 3. Browser classification
	browser := p.classifier.ClassifySingle(embedding)

	// 4. Forgery detection
	forgery := p.detector.DetectSingle(features, crossFeatures)

	// 5. Threat assessment
	threat := p.assessor.AssessSingle(embedding, &forgery, behavior)

	return &PipelineResult{
		Embedding:     embedding,
		Browser:       browser,
		Forgery:       forgery,
		Threat:        threat,
		RawFeatures:   features,
		CrossFeatures: crossFeatures,
	}
}

// InferFromFeatures executes the inference chain from an already-extracted feature vector.
func (p *ModelPipeline) InferFromFeatures(fv *core.FeatureVector, behavior []float64) *PipelineResult {
	p.mu.RLock()
	defer p.mu.RUnlock()

	features := EncodeFingerprintFromFeatureVector(fv)
	crossFeatures := ComputeCrossLayerFeatures(features)
	embedding := p.encoder.EncodeSingle(features)
	browser := p.classifier.ClassifySingle(embedding)
	forgery := p.detector.DetectSingle(features, crossFeatures)
	threat := p.assessor.AssessSingle(embedding, &forgery, behavior)

	return &PipelineResult{
		Embedding:     embedding,
		Browser:       browser,
		Forgery:       forgery,
		Threat:        threat,
		RawFeatures:   features,
		CrossFeatures: crossFeatures,
	}
}

// InferBatch performs batch inference, leveraging matrix operations for acceleration.
func (p *ModelPipeline) InferBatch(profs []*profiles.ClientProfile, behaviors [][]float64) []*PipelineResult {
	p.mu.RLock()
	defer p.mu.RUnlock()

	n := len(profs)
	results := make([]*PipelineResult, n)

	// 1. Batch feature encoding
	featureBatch := make([]float64, 0, n*FingerprintFeatureDim)
	crossBatch := make([]float64, 0, n*CrossLayerFeatureDim)
	for _, prof := range profs {
		fp := EncodeFingerprint(prof)
		featureBatch = append(featureBatch, fp...)
		cross := ComputeCrossLayerFeatures(fp)
		crossBatch = append(crossBatch, cross...)
	}

	fpTensor := NewTensor([]int{n, FingerprintFeatureDim}, featureBatch)

	// 2. Batch embedding
	embTensor := p.encoder.Encode(fpTensor)

	// 3. Batch classification
	browserPreds := p.classifier.Classify(embTensor)

	// 4. Batch forgery detection
	detInput := make([]float64, 0, n*(FingerprintFeatureDim+CrossLayerFeatureDim))
	for i := 0; i < n; i++ {
		fpStart := i * FingerprintFeatureDim
		crossStart := i * CrossLayerFeatureDim
		detInput = append(detInput, featureBatch[fpStart:fpStart+FingerprintFeatureDim]...)
		detInput = append(detInput, crossBatch[crossStart:crossStart+CrossLayerFeatureDim]...)
	}
	forgeryPreds := p.detector.Detect(NewTensor([]int{n, FingerprintFeatureDim + CrossLayerFeatureDim}, detInput))

	// 5. Batch threat assessment
	threatInputDim := EmbeddingDim + 1 + NumForgeryTypes + BehaviorFeatureDim
	threatData := make([]float64, n*threatInputDim)
	for i := 0; i < n; i++ {
		off := i * threatInputDim
		// Embedding
		embStart := i * EmbeddingDim
		copy(threatData[off:], embTensor.Data[embStart:embStart+EmbeddingDim])
		off += EmbeddingDim
		// Forgery result
		threatData[off] = forgeryPreds[i].ForgeryProb
		off++
		copy(threatData[off:off+NumForgeryTypes], forgeryPreds[i].TypeProbs)
		off += NumForgeryTypes
		// Behavioral features
		if i < len(behaviors) && len(behaviors[i]) >= BehaviorFeatureDim {
			copy(threatData[off:off+BehaviorFeatureDim], behaviors[i][:BehaviorFeatureDim])
		}
	}
	threatPreds := p.assessor.Assess(NewTensor([]int{n, threatInputDim}, threatData))

	// Assemble results
	for i := 0; i < n; i++ {
		fpStart := i * FingerprintFeatureDim
		crossStart := i * CrossLayerFeatureDim
		embStart := i * EmbeddingDim
		results[i] = &PipelineResult{
			Embedding:     append([]float64{}, embTensor.Data[embStart:embStart+EmbeddingDim]...),
			Browser:       browserPreds[i],
			Forgery:       forgeryPreds[i],
			Threat:        threatPreds[i],
			RawFeatures:   append([]float64{}, featureBatch[fpStart:fpStart+FingerprintFeatureDim]...),
			CrossFeatures: append([]float64{}, crossBatch[crossStart:crossStart+CrossLayerFeatureDim]...),
		}
	}
	return results
}

// SetTraining switches all models to training mode or inference mode.
func (p *ModelPipeline) SetTraining(training bool) {
	p.mu.Lock()
	defer p.mu.Unlock()
	p.encoder.Net.SetTraining(training)
	p.classifier.Net.SetTraining(training)
	p.detector.DetectorNet.SetTraining(training)
	p.detector.TypeNet.SetTraining(training)
	p.assessor.ThreatNet.SetTraining(training)
	p.assessor.ActionNet.SetTraining(training)
}
