// Package ml — pipeline.go provides end-to-end model inference and training pipelines.
//
// ┌─────────────────────────────────────────────────────────────────────┐
// │                  ModelPipeline — Inference Orchestration             │
// │                                                                     │
// │  Raw request                                                        │
// │    ↓ EncodeFingerprint()                                            │
// │  30-dim feature vector                                              │
// │    ↓ FingerprintEncoder.EncodeSingle()                              │
// │  32-dim embedding                                                   │
// │    ├→ BrowserClassifier.ClassifySingle()  → browser identification │
// │    │                                                                │
// │    │  30-dim features + 10-dim cross-layer features                 │
// │    ├→ ForgeryDetector.DetectSingle()      → forgery detection      │
// │    │                                                                │
// │    │  32-dim embedding + forgery result + 8-dim behavior features   │
// │    └→ ThreatAssessor.AssessSingle()       → threat + action        │
// │                                                                     │
// │  All model results aggregated into PipelineResult                   │
// └─────────────────────────────────────────────────────────────────────┘
//
// ┌─────────────────────────────────────────────────────────────────────┐
// │                  Trainer — Training Pipeline                        │
// │                                                                     │
// │  207 browser profiles → data augmentation → training samples        │
// │                                                                     │
// │  Phase 1: Encoder pre-training (triplet loss)                       │
// │    - Positive pairs: same browser + Gaussian noise                  │
// │    - Negative samples: different browser family                     │
// │                                                                     │
// │  Phase 2: Classifier training (cross-entropy)                       │
// │    - Freeze encoder, train classification head                      │
// │                                                                     │
// │  Phase 3: Forgery detector training (binary cross-entropy)          │
// │    - Real samples: from profiles                                    │
// │    - Forged samples: cross-browser layer mixing, headless features  │
// │                                                                     │
// │  Phase 4: Threat assessor training (cross-entropy)                  │
// │    - Initial labels: generated by rule engine                       │
// │    - Ongoing: online feedback fine-tuning                           │
// └─────────────────────────────────────────────────────────────────────┘
package ml

import (
	"encoding/json"
	"fmt"
	"math"
	"math/rand"
	"os"
	"sort"
	"sync"

	"github.com/vistone/fingerprint/modules/core"
	"github.com/vistone/fingerprint/modules/profiles"
)

// =========================================================================
// PipelineResult — inference pipeline output
// =========================================================================

// PipelineResult aggregates inference results from all models.
type PipelineResult struct {
	// Fingerprint embedding (32-dim)
	Embedding []float64

	// Browser identification result
	Browser BrowserPrediction

	// Forgery detection result
	Forgery ForgeryResult

	// Threat assessment result
	Threat ThreatPrediction

	// Raw features (for debugging/explainability)
	RawFeatures   []float64
	CrossFeatures []float64
}

// ModelPipeline is the end-to-end inference pipeline chaining four models.
type ModelPipeline struct {
	encoder    *FingerprintEncoder
	classifier *BrowserClassifier
	detector   *ForgeryDetector
	assessor   *ThreatAssessor
	trained    bool
	mu         sync.RWMutex
}

// Trained returns whether the pipeline has been trained or has loaded weights.
func (p *ModelPipeline) Trained() bool {
	p.mu.RLock()
	defer p.mu.RUnlock()
	return p.trained
}

// NewModelPipeline creates a new inference pipeline.
func NewModelPipeline() *ModelPipeline {
	return &ModelPipeline{
		encoder:    NewFingerprintEncoder(),
		classifier: NewBrowserClassifier(),
		detector:   NewForgeryDetector(),
		assessor:   NewThreatAssessor(),
	}
}

// Infer executes the full inference chain from a ClientProfile.
func (p *ModelPipeline) Infer(profile *profiles.ClientProfile, behavior []float64) *PipelineResult {
	p.mu.RLock()
	defer p.mu.RUnlock()

	// 1. Feature encoding
	features := EncodeFingerprint(profile)
	crossFeatures := ComputeCrossLayerFeatures(features)

	// 2. Fingerprint embedding
	embedding := p.encoder.EncodeSingle(features)

	// 3. Browser classification
	browser := p.classifier.ClassifySingle(embedding)

	// 4. Forgery detection
	forgery := p.detector.DetectSingle(features, crossFeatures)

	// 5. Threat assessment
	threat := p.assessor.AssessSingle(embedding, &forgery, behavior)

	return &PipelineResult{
		Embedding:     embedding,
		Browser:       browser,
		Forgery:       forgery,
		Threat:        threat,
		RawFeatures:   features,
		CrossFeatures: crossFeatures,
	}
}

// InferFromFeatures executes the inference chain from an already-extracted feature vector.
func (p *ModelPipeline) InferFromFeatures(fv *core.FeatureVector, behavior []float64) *PipelineResult {
	p.mu.RLock()
	defer p.mu.RUnlock()

	features := EncodeFingerprintFromFeatureVector(fv)
	crossFeatures := ComputeCrossLayerFeatures(features)
	embedding := p.encoder.EncodeSingle(features)
	browser := p.classifier.ClassifySingle(embedding)
	forgery := p.detector.DetectSingle(features, crossFeatures)
	threat := p.assessor.AssessSingle(embedding, &forgery, behavior)

	return &PipelineResult{
		Embedding:     embedding,
		Browser:       browser,
		Forgery:       forgery,
		Threat:        threat,
		RawFeatures:   features,
		CrossFeatures: crossFeatures,
	}
}

// InferBatch performs batch inference, leveraging matrix operations for acceleration.
func (p *ModelPipeline) InferBatch(profs []*profiles.ClientProfile, behaviors [][]float64) []*PipelineResult {
	p.mu.RLock()
	defer p.mu.RUnlock()

	n := len(profs)
	results := make([]*PipelineResult, n)

	// 1. Batch feature encoding
	featureBatch := make([]float64, 0, n*FingerprintFeatureDim)
	crossBatch := make([]float64, 0, n*CrossLayerFeatureDim)
	for _, prof := range profs {
		fp := EncodeFingerprint(prof)
		featureBatch = append(featureBatch, fp...)
		cross := ComputeCrossLayerFeatures(fp)
		crossBatch = append(crossBatch, cross...)
	}

	fpTensor := NewTensor([]int{n, FingerprintFeatureDim}, featureBatch)

	// 2. Batch embedding
	embTensor := p.encoder.Encode(fpTensor)

	// 3. Batch classification
	browserPreds := p.classifier.Classify(embTensor)

	// 4. Batch forgery detection
	detInput := make([]float64, 0, n*(FingerprintFeatureDim+CrossLayerFeatureDim))
	for i := 0; i < n; i++ {
		fpStart := i * FingerprintFeatureDim
		crossStart := i * CrossLayerFeatureDim
		detInput = append(detInput, featureBatch[fpStart:fpStart+FingerprintFeatureDim]...)
		detInput = append(detInput, crossBatch[crossStart:crossStart+CrossLayerFeatureDim]...)
	}
	forgeryPreds := p.detector.Detect(NewTensor([]int{n, FingerprintFeatureDim + CrossLayerFeatureDim}, detInput))

	// 5. Batch threat assessment
	threatInputDim := EmbeddingDim + 1 + NumForgeryTypes + BehaviorFeatureDim
	threatData := make([]float64, n*threatInputDim)
	for i := 0; i < n; i++ {
		off := i * threatInputDim
		// Embedding
		embStart := i * EmbeddingDim
		copy(threatData[off:], embTensor.Data[embStart:embStart+EmbeddingDim])
		off += EmbeddingDim
		// Forgery result
		threatData[off] = forgeryPreds[i].ForgeryProb
		off++
		copy(threatData[off:off+NumForgeryTypes], forgeryPreds[i].TypeProbs)
		off += NumForgeryTypes
		// Behavioral features
		if i < len(behaviors) && len(behaviors[i]) >= BehaviorFeatureDim {
			copy(threatData[off:off+BehaviorFeatureDim], behaviors[i][:BehaviorFeatureDim])
		}
	}
	threatPreds := p.assessor.Assess(NewTensor([]int{n, threatInputDim}, threatData))

	// Assemble results
	for i := 0; i < n; i++ {
		fpStart := i * FingerprintFeatureDim
		crossStart := i * CrossLayerFeatureDim
		embStart := i * EmbeddingDim
		results[i] = &PipelineResult{
			Embedding:     append([]float64{}, embTensor.Data[embStart:embStart+EmbeddingDim]...),
			Browser:       browserPreds[i],
			Forgery:       forgeryPreds[i],
			Threat:        threatPreds[i],
			RawFeatures:   append([]float64{}, featureBatch[fpStart:fpStart+FingerprintFeatureDim]...),
			CrossFeatures: append([]float64{}, crossBatch[crossStart:crossStart+CrossLayerFeatureDim]...),
		}
	}
	return results
}

// SetTraining switches all models to training mode or inference mode.
func (p *ModelPipeline) SetTraining(training bool) {
	p.mu.Lock()
	defer p.mu.Unlock()
	p.encoder.Net.SetTraining(training)
	p.classifier.Net.SetTraining(training)
	p.detector.DetectorNet.SetTraining(training)
	p.detector.TypeNet.SetTraining(training)
	p.assessor.ThreatNet.SetTraining(training)
	p.assessor.ActionNet.SetTraining(training)
}

// =========================================================================
// Trainer — train all models from browser profiles
// =========================================================================

// NeuralTrainerConfig holds neural network training configuration.
type NeuralTrainerConfig struct {
	Epochs          int     // number of training epochs
	BatchSize       int     // mini-batch size
	LearningRate    float64 // Adam learning rate
	AugmentNoise    float64 // data augmentation noise stddev
	TripletMargin   float64 // triplet loss margin
	ForgeryRatio    float64 // ratio of forged to real samples
	ValidationSplit float64 // validation set ratio
}

// DefaultNeuralTrainerConfig is the default training configuration.
var DefaultNeuralTrainerConfig = &NeuralTrainerConfig{
	Epochs:          100,
	BatchSize:       32,
	LearningRate:    0.001,
	AugmentNoise:    0.05,
	TripletMargin:   1.0,
	ForgeryRatio:    1.5,
	ValidationSplit: 0.2,
}

// TrainingMetrics holds training metrics.
type TrainingMetrics struct {
	Epoch       int
	EncoderLoss float64
	ClassLoss   float64
	ForgeryLoss float64
	ThreatLoss  float64
	ValAccuracy float64
	ForgeryAUC  float64
}

// NeuralTrainer is the neural network training pipeline.
type NeuralTrainer struct {
	Pipeline *ModelPipeline
	Config   *NeuralTrainerConfig
	Metrics  []TrainingMetrics
}

// NewNeuralTrainer creates a new neural network training pipeline.
func NewNeuralTrainer(pipeline *ModelPipeline, config *NeuralTrainerConfig) *NeuralTrainer {
	if config == nil {
		config = DefaultNeuralTrainerConfig
	}
	return &NeuralTrainer{
		Pipeline: pipeline,
		Config:   config,
	}
}

// TrainFromProfiles trains all models from browser profiles.
// Main training entry: load 207 profiles → data augmentation → multi-phase training.
func (t *NeuralTrainer) TrainFromProfiles(registry *profiles.ProfileRegistry) error {
	allProfiles := registry.GetAll()
	if len(allProfiles) == 0 {
		return fmt.Errorf("no profiles available for training")
	}

	// Build training data
	trainSet, valSet := t.buildTrainingData(allProfiles)

	// Phase 1: Encoder pre-training (triplet loss)
	if err := t.trainEncoder(trainSet); err != nil {
		return fmt.Errorf("encoder training failed: %w", err)
	}

	// Phase 2: Browser classifier training
	if err := t.trainClassifier(trainSet, valSet); err != nil {
		return fmt.Errorf("classifier training failed: %w", err)
	}

	// Phase 3: Forgery detector training
	if err := t.trainForgeryDetector(trainSet); err != nil {
		return fmt.Errorf("forgery detector training failed: %w", err)
	}

	// Phase 4: Threat assessor training
	if err := t.trainThreatAssessor(trainSet); err != nil {
		return fmt.Errorf("threat assessor training failed: %w", err)
	}

	t.Pipeline.mu.Lock()
	t.Pipeline.trained = true
	t.Pipeline.mu.Unlock()

	return nil
}

// profileSample is an internal training sample.
type profileSample struct {
	Features    []float64
	FamilyLabel int
	ProfileID   string
	BrowserType core.BrowserType
}

// buildTrainingData converts profiles into training samples and splits into train/val sets.
func (t *NeuralTrainer) buildTrainingData(allProfiles []profiles.ClientProfile) (train, val []profileSample) {
	// Group by browser family
	familyMap := make(map[core.BrowserType][]profiles.ClientProfile)
	for _, p := range allProfiles {
		familyMap[p.BrowserType] = append(familyMap[p.BrowserType], p)
	}

	familyLabels := browserFamilyLabelMap()

	var samples []profileSample
	for _, p := range allProfiles {
		features := EncodeFingerprint(&p)
		label := familyLabels[p.BrowserType]
		samples = append(samples, profileSample{
			Features:    features,
			FamilyLabel: label,
			ProfileID:   p.ID,
			BrowserType: p.BrowserType,
		})
		// Data augmentation: generate variants with varying noise levels
		augNoises := []float64{
			t.Config.AugmentNoise * 0.5,
			t.Config.AugmentNoise * 0.75,
			t.Config.AugmentNoise,
			t.Config.AugmentNoise,
			t.Config.AugmentNoise * 1.25,
			t.Config.AugmentNoise * 1.5,
			t.Config.AugmentNoise * 2.0,
			t.Config.AugmentNoise * 2.5,
		}
		for _, noise := range augNoises {
			augFeatures := make([]float64, len(features))
			copy(augFeatures, features)
			for i := range augFeatures {
				augFeatures[i] += rand.NormFloat64() * noise
				augFeatures[i] = math.Max(0, math.Min(1, augFeatures[i]))
			}
			samples = append(samples, profileSample{
				Features:    augFeatures,
				FamilyLabel: label,
				ProfileID:   p.ID,
				BrowserType: p.BrowserType,
			})
		}
	}

	// Shuffle and split
	rand.Shuffle(len(samples), func(i, j int) { samples[i], samples[j] = samples[j], samples[i] })
	splitIdx := int(float64(len(samples)) * (1.0 - t.Config.ValidationSplit))
	return samples[:splitIdx], samples[splitIdx:]
}

// browserFamilyLabelMap returns the mapping from browser type to label index.
func browserFamilyLabelMap() map[core.BrowserType]int {
	return map[core.BrowserType]int{
		core.BrowserChrome:  0,
		core.BrowserFirefox: 1,
		core.BrowserSafari:  2,
		core.BrowserEdge:    3,
		core.BrowserOpera:   4,
		core.BrowserBrave:   5,
		core.BrowserSamsung: 6,
	}
}

// =========================================================================
// Phase 1: Encoder training — triplet loss
// =========================================================================

func (t *NeuralTrainer) trainEncoder(samples []profileSample) error {
	cfg := t.Config
	enc := t.Pipeline.encoder
	enc.Net.SetTraining(true)
	defer enc.Net.SetTraining(false)

	params := enc.Net.Params()
	optimizer := NewAdamOptimizer(params, cfg.LearningRate)
	scheduler := NewWarmupCosineAnnealingLR(cfg.LearningRate, cfg.LearningRate*0.01, 5)
	tripletMargin := cfg.TripletMargin

	// Group indices by family
	familyIdx := make(map[int][]int)
	for i, s := range samples {
		familyIdx[s.FamilyLabel] = append(familyIdx[s.FamilyLabel], i)
	}
	families := make([]int, 0, len(familyIdx))
	for f := range familyIdx {
		families = append(families, f)
	}
	sort.Ints(families)

	for epoch := 0; epoch < cfg.Epochs; epoch++ {
		scheduler.StepLR(optimizer, epoch, cfg.Epochs)
		totalLoss := 0.0
		count := 0

		// Generate triplets with semi-hard negative mining
		for _, fam := range families {
			indices := familyIdx[fam]
			if len(indices) < 2 {
				continue
			}

			batchSize := min(cfg.BatchSize, len(indices)/2)
			if batchSize < 1 {
				batchSize = 1
			}

			// Pre-compute embeddings for hard negative selection
			var candidateNegs []int
			for _, otherFam := range families {
				if otherFam != fam {
					candidateNegs = append(candidateNegs, familyIdx[otherFam]...)
				}
			}
			if len(candidateNegs) == 0 {
				continue
			}

			anchors := make([]float64, 0, batchSize*FingerprintFeatureDim)
			positives := make([]float64, 0, batchSize*FingerprintFeatureDim)
			negatives := make([]float64, 0, batchSize*FingerprintFeatureDim)

			for b := 0; b < batchSize; b++ {
				aIdx := indices[rand.Intn(len(indices))]
				pIdx := indices[rand.Intn(len(indices))]

				// Semi-hard negative mining: pick closest negative
				anchorEmb := enc.EncodeSingle(samples[aIdx].Features)
				bestNegIdx := candidateNegs[rand.Intn(len(candidateNegs))]
				bestNegDist := math.MaxFloat64

				// Sample a subset of candidates for efficiency
				numCandidates := min(16, len(candidateNegs))
				for c := 0; c < numCandidates; c++ {
					cIdx := candidateNegs[rand.Intn(len(candidateNegs))]
					negEmb := enc.EncodeSingle(samples[cIdx].Features)
					dist := 0.0
					for d := 0; d < len(anchorEmb); d++ {
						diff := anchorEmb[d] - negEmb[d]
						dist += diff * diff
					}
					if dist < bestNegDist {
						bestNegDist = dist
						bestNegIdx = cIdx
					}
				}

				anchors = append(anchors, samples[aIdx].Features...)
				positives = append(positives, samples[pIdx].Features...)
				negatives = append(negatives, samples[bestNegIdx].Features...)
			}

			anchorT := NewTensor([]int{batchSize, FingerprintFeatureDim}, anchors)
			posT := NewTensor([]int{batchSize, FingerprintFeatureDim}, positives)
			negT := NewTensor([]int{batchSize, FingerprintFeatureDim}, negatives)

			enc.Net.ZeroGrad()
			anchorEmb := enc.Encode(anchorT)
			posEmb := enc.Encode(posT)
			negEmb := enc.Encode(negT)

			loss, anchorGrad, _, _ := TripletMarginLoss(anchorEmb, posEmb, negEmb, tripletMargin)

			enc.Net.Backward(anchorGrad)
			ClipGradNorm(params, 5.0)
			optimizer.Step()

			totalLoss += loss
			count++
		}

		if count > 0 {
			t.recordMetric(epoch, totalLoss/float64(count), 0, 0, 0, 0, 0)
		}
	}
	return nil
}

// =========================================================================
// Phase 2: Classifier training — cross-entropy
// =========================================================================

func (t *NeuralTrainer) trainClassifier(trainSet, valSet []profileSample) error {
	cfg := t.Config
	enc := t.Pipeline.encoder
	cls := t.Pipeline.classifier
	cls.Net.SetTraining(true)
	defer cls.Net.SetTraining(false)

	params := cls.Net.Params()
	optimizer := NewAdamOptimizer(params, cfg.LearningRate)
	scheduler := NewWarmupCosineAnnealingLR(cfg.LearningRate, cfg.LearningRate*0.01, 5)

	for epoch := 0; epoch < cfg.Epochs; epoch++ {
		scheduler.StepLR(optimizer, epoch, cfg.Epochs)
		totalLoss := 0.0
		count := 0

		// Mini-batch training
		for start := 0; start < len(trainSet); start += cfg.BatchSize {
			end := start + cfg.BatchSize
			if end > len(trainSet) {
				end = len(trainSet)
			}
			batchSamples := trainSet[start:end]
			batchN := len(batchSamples)

			// Encode → embedding (encoder is frozen)
			fpData := make([]float64, 0, batchN*FingerprintFeatureDim)
			targets := make([]int, batchN)
			for i, s := range batchSamples {
				fpData = append(fpData, s.Features...)
				targets[i] = s.FamilyLabel
			}

			embeddings := enc.Encode(NewTensor([]int{batchN, FingerprintFeatureDim}, fpData))

			// Forward pass
			cls.Net.ZeroGrad()
			output := cls.Net.Forward(embeddings)

			// Compute loss
			lossVal, grad := CrossEntropyLoss(output, targets)

			// Backpropagation
			cls.Net.Backward(grad)
			ClipGradNorm(params, 5.0)
			optimizer.Step()

			totalLoss += lossVal
			count++
		}

		// Validation accuracy
		valAcc := t.evaluateClassifier(enc, cls, valSet)

		if count > 0 {
			t.recordMetric(epoch, 0, totalLoss/float64(count), 0, 0, valAcc, 0)
		}
	}
	return nil
}

func (t *NeuralTrainer) evaluateClassifier(enc *FingerprintEncoder, cls *BrowserClassifier, valSet []profileSample) float64 {
	if len(valSet) == 0 {
		return 0
	}
	correct := 0
	familyLabels := browserFamilyLabelMap()
	for _, s := range valSet {
		emb := enc.EncodeSingle(s.Features)
		pred := cls.ClassifySingle(emb)
		if familyLabels[pred.Family] == s.FamilyLabel {
			correct++
		}
	}
	return float64(correct) / float64(len(valSet))
}

// =========================================================================
// Phase 3: Forgery detector training
// =========================================================================

func (t *NeuralTrainer) trainForgeryDetector(realSamples []profileSample) error {
	cfg := t.Config
	det := t.Pipeline.detector
	det.DetectorNet.SetTraining(true)
	det.TypeNet.SetTraining(true)
	defer det.DetectorNet.SetTraining(false)
	defer det.TypeNet.SetTraining(false)

	allParams := append(det.DetectorNet.Params(), det.TypeNet.Params()...)
	optimizer := NewAdamOptimizer(allParams, cfg.LearningRate)
	scheduler := NewWarmupCosineAnnealingLR(cfg.LearningRate, cfg.LearningRate*0.01, 5)

	inputDim := FingerprintFeatureDim + CrossLayerFeatureDim

	for epoch := 0; epoch < cfg.Epochs; epoch++ {
		scheduler.StepLR(optimizer, epoch, cfg.Epochs)
		totalLoss := 0.0
		count := 0

		for start := 0; start < len(realSamples); start += cfg.BatchSize {
			end := start + cfg.BatchSize
			if end > len(realSamples) {
				end = len(realSamples)
			}
			batchReal := realSamples[start:end]
			batchN := len(batchReal)

			// Compute number of forged samples
			numForgery := int(float64(batchN) * cfg.ForgeryRatio)
			if numForgery < 1 {
				numForgery = 1
			}
			totalBatch := batchN + numForgery

			inputData := make([]float64, 0, totalBatch*inputDim)
			targetData := make([]float64, totalBatch)

			// Real samples (label = 0, i.e. not forged)
			for _, s := range batchReal {
				cross := ComputeCrossLayerFeatures(s.Features)
				inputData = append(inputData, s.Features...)
				inputData = append(inputData, cross...)
			}

			// Forged samples (label = 1)
			for f := 0; f < numForgery; f++ {
				forged := t.generateForgedSample(realSamples)
				cross := ComputeCrossLayerFeatures(forged)
				inputData = append(inputData, forged...)
				inputData = append(inputData, cross...)
				targetData[batchN+f] = 1.0 // forged
			}

			input := NewTensor([]int{totalBatch, inputDim}, inputData)

			// Detection network forward pass
			det.DetectorNet.ZeroGrad()
			output := det.DetectorNet.Forward(input)

			// Binary cross-entropy loss
			lossVal, grad := BinaryCrossEntropyLoss(output, targetData)
			det.DetectorNet.Backward(grad)
			ClipGradNorm(allParams, 5.0)
			optimizer.Step()

			totalLoss += lossVal
			count++
		}

		if count > 0 {
			t.recordMetric(epoch, 0, 0, totalLoss/float64(count), 0, 0, 0)
		}
	}
	return nil
}

// generateForgedSample generates a forged fingerprint sample.
// Multiple strategies to simulate different forgery types:
//   - Cross-browser layer mixing (anti-detect tool pattern)
//   - Headless browser simulation (missing JS features)
//   - Proxy/MITM pattern (TCP anomalies)
//   - Noise injection (generic tool fingerprint)
func (t *NeuralTrainer) generateForgedSample(samples []profileSample) []float64 {
	forged := make([]float64, FingerprintFeatureDim)

	strategy := rand.Intn(4)
	s1 := samples[rand.Intn(len(samples))]
	s2 := samples[rand.Intn(len(samples))]

	switch strategy {
	case 0: // Cross-browser layer mixing (anti-detect)
		// TLS from one browser, HTTP/2 from another
		copy(forged[0:8], s1.Features[0:8])
		copy(forged[8:14], s2.Features[8:14])
		if rand.Float64() < 0.5 {
			copy(forged[14:18], s1.Features[14:18])
		} else {
			copy(forged[14:18], s2.Features[14:18])
		}
		// JS features: partial or mismatched
		forged[18] = rand.Float64() * 0.3 // low canvas (tool fingerprint)
		forged[19] = rand.Float64() * 0.3 // low webgl
		forged[25] = rand.Float64()*0.3 + 0.4
		forged[26] = s1.Features[26]          // keep original UA
		forged[27] = s2.Features[27]          // but entropy from different browser
		forged[28] = rand.Float64()*0.3 + 0.3 // moderate tool marker

	case 1: // Headless browser (Puppeteer/Selenium)
		copy(forged, s1.Features)
		// Missing or anomalous JS features
		forged[18] = 0                        // no canvas
		forged[19] = 0                        // no webgl
		forged[20] = 0                        // no audio
		forged[21] = rand.Float64() * 0.05    // very few fonts
		forged[22] = rand.Float64() * 0.2     // low storage
		forged[23] = 0                        // no webrtc
		forged[24] = 0.25                     // generic 4 cores
		forged[25] = rand.Float64()*0.3 + 0.7 // high headless score
		forged[28] = rand.Float64()*0.2 + 0.5 // tool marker present

	case 2: // Proxy/MITM (TCP anomalies)
		copy(forged, s1.Features)
		// TCP layer inconsistencies
		forged[14] = 0.5 + rand.Float64()*0.5 // anomalous TTL
		forged[15] = rand.Float64() * 0.3     // unusual window
		forged[16] = rand.Float64() * 0.4     // unusual MSS
		forged[17] = 0                        // no timestamps (proxy stripped)
		forged[29] = rand.Float64()*0.2 + 0.3 // mild behavior anomaly

	case 3: // Noise injection (generic tool)
		// Start with random mix
		for i := 0; i < FingerprintFeatureDim; i++ {
			if rand.Float64() < 0.5 {
				forged[i] = s1.Features[i]
			} else {
				forged[i] = s2.Features[i]
			}
		}
		// Add significant noise
		for i := range forged {
			forged[i] += rand.NormFloat64() * 0.1
		}
		forged[28] = rand.Float64()*0.3 + 0.2 // some tool marker
	}

	// Final noise + clamp
	for i := range forged {
		forged[i] += rand.NormFloat64() * 0.02
		forged[i] = math.Max(0, math.Min(1, forged[i]))
	}
	return forged
}

// =========================================================================
// Phase 4: Threat assessor training
// =========================================================================

func (t *NeuralTrainer) trainThreatAssessor(samples []profileSample) error {
	cfg := t.Config
	enc := t.Pipeline.encoder
	det := t.Pipeline.detector
	assessor := t.Pipeline.assessor
	assessor.ThreatNet.SetTraining(true)
	assessor.ActionNet.SetTraining(true)
	defer assessor.ThreatNet.SetTraining(false)
	defer assessor.ActionNet.SetTraining(false)

	allParams := append(assessor.ThreatNet.Params(), assessor.ActionNet.Params()...)
	optimizer := NewAdamOptimizer(allParams, cfg.LearningRate)
	scheduler := NewWarmupCosineAnnealingLR(cfg.LearningRate, cfg.LearningRate*0.01, 5)

	inputDim := EmbeddingDim + 1 + NumForgeryTypes + BehaviorFeatureDim

	for epoch := 0; epoch < cfg.Epochs; epoch++ {
		scheduler.StepLR(optimizer, epoch, cfg.Epochs)
		totalLoss := 0.0
		count := 0

		for start := 0; start < len(samples); start += cfg.BatchSize {
			end := start + cfg.BatchSize
			if end > len(samples) {
				end = len(samples)
			}
			batchSamples := samples[start:end]
			batchN := len(batchSamples)

			inputData := make([]float64, batchN*inputDim)
			threatTargets := make([]int, batchN)

			for i, s := range batchSamples {
				emb := enc.EncodeSingle(s.Features)
				cross := ComputeCrossLayerFeatures(s.Features)
				forgery := det.DetectSingle(s.Features, cross)

				off := i * inputDim
				copy(inputData[off:], emb)
				off += EmbeddingDim
				inputData[off] = forgery.ForgeryProb
				off++
				copy(inputData[off:off+NumForgeryTypes], forgery.TypeProbs)
				off += NumForgeryTypes
				// Synthetic behavioral features to prevent zero-feature bias
				behavior := t.generateSyntheticBehavior(s, &forgery)
				copy(inputData[off:off+BehaviorFeatureDim], behavior)

				threatTargets[i] = t.generateThreatLabel(s, &forgery)
			}

			input := NewTensor([]int{batchN, inputDim}, inputData)

			assessor.ThreatNet.ZeroGrad()
			output := assessor.ThreatNet.Forward(input)
			lossVal, grad := CrossEntropyLoss(output, threatTargets)
			assessor.ThreatNet.Backward(grad)
			ClipGradNorm(allParams, 5.0)
			optimizer.Step()

			totalLoss += lossVal
			count++
		}

		if count > 0 {
			t.recordMetric(epoch, 0, 0, 0, totalLoss/float64(count), 0, 0)
		}
	}
	return nil
}

// generateThreatLabel generates a rule-based label from sample features and forgery detection results.
func (t *NeuralTrainer) generateThreatLabel(s profileSample, forgery *ForgeryResult) int {
	if forgery.ForgeryProb > 0.7 {
		switch forgery.ForgeryType {
		case ForgeryHeadless:
			return int(ThreatBot)
		case ForgeryAntiDetect:
			return int(ThreatFingerprintSpoof)
		case ForgeryProxy:
			return int(ThreatEvasion)
		}
		return int(ThreatFingerprintSpoof)
	}
	// Check for behavioral anomaly signals from features
	if s.Features[28] > 0.3 { // tool marker
		return int(ThreatBot)
	}
	if s.Features[29] > 0.3 { // behavior pattern anomaly
		return int(ThreatBehavioralAnomaly)
	}
	return int(ThreatNone)
}

// generateSyntheticBehavior generates synthetic behavioral features for training.
// This prevents the model from learning to ignore the behavior input dimensions.
func (t *NeuralTrainer) generateSyntheticBehavior(s profileSample, forgery *ForgeryResult) []float64 {
	behavior := make([]float64, BehaviorFeatureDim)

	if forgery.ForgeryProb > 0.5 {
		// Forged clients tend to have anomalous behavior
		behavior[0] = rand.Float64()*0.3 + 0.5 // high fingerprint switch rate
		behavior[1] = rand.Float64()*0.4 + 0.4 // high request rate
		behavior[2] = rand.Float64() * 0.4     // low consistency
		behavior[3] = rand.Float64()*0.3 + 0.5 // rising risk trend
		behavior[4] = rand.Float64() * 0.3     // few observations
		behavior[5] = rand.Float64()*0.3 + 0.5 // high unique FP ratio
		behavior[6] = rand.Float64() * 0.3     // short sessions
		behavior[7] = rand.Float64()*0.3 + 0.3 // burst indicator
	} else {
		// Normal clients have stable behavior
		behavior[0] = rand.Float64() * 0.2     // low switch rate
		behavior[1] = rand.Float64() * 0.3     // moderate request rate
		behavior[2] = rand.Float64()*0.3 + 0.6 // high consistency
		behavior[3] = rand.Float64() * 0.3     // low risk trend
		behavior[4] = rand.Float64()*0.3 + 0.4 // many observations
		behavior[5] = rand.Float64() * 0.3     // low unique FP ratio
		behavior[6] = rand.Float64()*0.3 + 0.5 // longer sessions
		behavior[7] = rand.Float64() * 0.2     // no burst
	}

	// Add noise
	for i := range behavior {
		behavior[i] += rand.NormFloat64() * 0.05
		behavior[i] = math.Max(0, math.Min(1, behavior[i]))
	}
	return behavior
}

func (t *NeuralTrainer) recordMetric(epoch int, encLoss, clsLoss, forLoss, thrLoss, valAcc, forAUC float64) {
	// If same epoch already has a record, merge
	for i := range t.Metrics {
		if t.Metrics[i].Epoch == epoch {
			if encLoss > 0 {
				t.Metrics[i].EncoderLoss = encLoss
			}
			if clsLoss > 0 {
				t.Metrics[i].ClassLoss = clsLoss
			}
			if forLoss > 0 {
				t.Metrics[i].ForgeryLoss = forLoss
			}
			if thrLoss > 0 {
				t.Metrics[i].ThreatLoss = thrLoss
			}
			if valAcc > 0 {
				t.Metrics[i].ValAccuracy = valAcc
			}
			if forAUC > 0 {
				t.Metrics[i].ForgeryAUC = forAUC
			}
			return
		}
	}
	t.Metrics = append(t.Metrics, TrainingMetrics{
		Epoch:       epoch,
		EncoderLoss: encLoss,
		ClassLoss:   clsLoss,
		ForgeryLoss: forLoss,
		ThreatLoss:  thrLoss,
		ValAccuracy: valAcc,
		ForgeryAUC:  forAUC,
	})
}

// =========================================================================
// Model serialization — save/load trained model weights
// =========================================================================

// ModelWeights holds serialized model weights.
type ModelWeights struct {
	Version     string            `json:"version"`
	Encoder     []SerializedParam `json:"encoder"`
	Classifier  []SerializedParam `json:"classifier"`
	DetectorNet []SerializedParam `json:"detector_net"`
	TypeNet     []SerializedParam `json:"type_net"`
	ThreatNet   []SerializedParam `json:"threat_net"`
	ActionNet   []SerializedParam `json:"action_net"`
	Metrics     []TrainingMetrics `json:"metrics,omitempty"`
}

// SerializedParam holds a serialized parameter.
type SerializedParam struct {
	Shape []int     `json:"shape"`
	Data  []float64 `json:"data"`
}

// SaveWeights saves model weights to a file.
func (p *ModelPipeline) SaveWeights(path string) error {
	p.mu.RLock()
	defer p.mu.RUnlock()

	weights := &ModelWeights{
		Version:     "1.0.14",
		Encoder:     serializeParams(p.encoder.Net.Params()),
		Classifier:  serializeParams(p.classifier.Net.Params()),
		DetectorNet: serializeParams(p.detector.DetectorNet.Params()),
		TypeNet:     serializeParams(p.detector.TypeNet.Params()),
		ThreatNet:   serializeParams(p.assessor.ThreatNet.Params()),
		ActionNet:   serializeParams(p.assessor.ActionNet.Params()),
	}

	data, err := json.Marshal(weights)
	if err != nil {
		return fmt.Errorf("marshal weights: %w", err)
	}
	return os.WriteFile(path, data, 0600)
}

// LoadWeights loads model weights from a file.
func (p *ModelPipeline) LoadWeights(path string) error {
	p.mu.Lock()
	defer p.mu.Unlock()

	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read weights: %w", err)
	}

	var weights ModelWeights
	if err := json.Unmarshal(data, &weights); err != nil {
		return fmt.Errorf("unmarshal weights: %w", err)
	}

	deserializeParams(p.encoder.Net.Params(), weights.Encoder)
	deserializeParams(p.classifier.Net.Params(), weights.Classifier)
	deserializeParams(p.detector.DetectorNet.Params(), weights.DetectorNet)
	deserializeParams(p.detector.TypeNet.Params(), weights.TypeNet)
	deserializeParams(p.assessor.ThreatNet.Params(), weights.ThreatNet)
	deserializeParams(p.assessor.ActionNet.Params(), weights.ActionNet)

	p.trained = true
	return nil
}

func serializeParams(params []*Param) []SerializedParam {
	out := make([]SerializedParam, len(params))
	for i, p := range params {
		out[i] = SerializedParam{
			Shape: append([]int{}, p.Value.Shape...),
			Data:  append([]float64{}, p.Value.Data...),
		}
	}
	return out
}

func deserializeParams(params []*Param, serialized []SerializedParam) {
	for i := range params {
		if i >= len(serialized) {
			break
		}
		s := serialized[i]
		if len(s.Data) == len(params[i].Value.Data) {
			copy(params[i].Value.Data, s.Data)
			params[i].Value.Shape = append([]int{}, s.Shape...)
		}
	}
}

// =========================================================================
// Helper functions
// =========================================================================
