package agent

import (
	"fmt"
	"sync"
	"time"
)

// StrategyEngine adaptive strategy engine
//
// Manages a set of dynamic detection strategies, each describing detection conditions and response actions for a threat pattern.
// The engine has two capabilities:
//
//  1. Rule evaluation: execute all active strategies for each observation + behavior profile
//  2. Self-evolution (Evolve): automatically generate/eliminate strategies based on accumulated observation statistics
type StrategyEngine struct {
	config     *AgentConfig
	memory     *Memory
	strategies []*Strategy
	mu         sync.RWMutex

	// Learned pattern count
	learnedPatterns int
}

// Strategy a single adaptive strategy
type Strategy struct {
	ID          string
	Name        string
	Description string
	ThreatClass ThreatClass
	Action      ActionType
	Priority    int // Higher value evaluated first

	// Condition function: input observation + behavior profile, return whether triggered
	Condition func(obs *Observation, profile *BehaviorSummary) bool

	// statistics
	HitCount  int
	MissCount int
	CreatedAt time.Time
	Learned   bool // whether automatically generated by evolution
	Enabled   bool
}

// StrategyInfo strategy summary (exposed externally, no functions)
type StrategyInfo struct {
	ID          string      `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	ThreatClass ThreatClass `json:"threat_class"`
	Action      ActionType  `json:"action"`
	Priority    int         `json:"priority"`
	HitCount    int         `json:"hit_count"`
	Learned     bool        `json:"learned"`
	Enabled     bool        `json:"enabled"`
}

// NewStrategyEngine create strategy engine and register builtin strategies
func NewStrategyEngine(config *AgentConfig, memory *Memory) *StrategyEngine {
	se := &StrategyEngine{
		config:     config,
		memory:     memory,
		strategies: make([]*Strategy, 0, 16),
	}
	se.registerBuiltinStrategies()
	return se
}

// registerBuiltinStrategies register builtin strategies (baseline)
func (se *StrategyEngine) registerBuiltinStrategies() {
	cfg := se.config
	se.strategies = append(se.strategies,
		// S1: Fast fingerprint switching → possible fingerprint forging/rotation tool
		&Strategy{
			ID:          "builtin_fp_switch",
			Name:        "Fast Fingerprint Switching Detection",
			Description: "Client frequently switches fingerprints in short time, suspected anti-detection tool",
			ThreatClass: ThreatFingerprintSpoof,
			Action:      ActionChallenge,
			Priority:    90,
			Condition: func(obs *Observation, profile *BehaviorSummary) bool {
				return profile.FPSwitchRate > cfg.FPSwitchRateThreshold
			},
			CreatedAt: time.Now(),
			Enabled:   true,
		},
		// S2: Low consistency → behavioral anomaly
		&Strategy{
			ID:          "builtin_low_consistency",
			Name:        "Low Fingerprint Consistency Detection",
			Description: "Client fingerprint/classification result consistency extremely low, behavioral pattern anomaly",
			ThreatClass: ThreatBehavioralAnomaly,
			Action:      ActionMonitor,
			Priority:    70,
			Condition: func(obs *Observation, profile *BehaviorSummary) bool {
				return profile.TotalObservations >= 3 &&
					profile.ConsistencyScore < cfg.ConsistencyThreshold
			},
			CreatedAt: time.Now(),
			Enabled:   true,
		},
		// S3: Request burst → possible automation tool
		&Strategy{
			ID:          "builtin_request_burst",
			Name:        "Request Burst Detection",
			Description: "Request frequency abnormally high, suspected automation tool or crawler",
			ThreatClass: ThreatBot,
			Action:      ActionThrottle,
			Priority:    80,
			Condition: func(obs *Observation, profile *BehaviorSummary) bool {
				if profile.AvgRequestInterval <= 0 || profile.TotalObservations < 5 {
					return false
				}
				reqPerSec := 1.0 / profile.AvgRequestInterval
				return reqPerSec > cfg.RequestBurstThreshold
			},
			CreatedAt: time.Now(),
			Enabled:   true,
		},
		// S4: Risk continuously rising → escalate response
		&Strategy{
			ID:          "builtin_risk_escalation",
			Name:        "Risk Rising Trend Detection",
			Description: "Client risk score continuously rising, need to escalate protection",
			ThreatClass: ThreatEvasion,
			Action:      ActionChallenge,
			Priority:    85,
			Condition: func(obs *Observation, profile *BehaviorSummary) bool {
				return profile.RiskTrend > 0.5 && profile.TotalObservations >= 5
			},
			CreatedAt: time.Now(),
			Enabled:   true,
		},
		// S5: High-risk rule triggered + low ML confidence → block
		&Strategy{
			ID:          "builtin_high_risk_block",
			Name:        "High-Risk Comprehensive Block",
			Description: "Multiple high-risk signals triggered simultaneously: rule hit + ML low confidence + behavioral anomaly",
			ThreatClass: ThreatEvasion,
			Action:      ActionBlock,
			Priority:    95,
			Condition: func(obs *Observation, profile *BehaviorSummary) bool {
				if obs.RiskAssessment == nil || obs.Classification == nil {
					return false
				}
				highRisk := obs.RiskAssessment.Score > 0.7
				lowConf := obs.Classification.Confidence < 0.3
				badBehavior := profile.ConsistencyScore < 0.3
				return highRisk && lowConf && badBehavior
			},
			CreatedAt: time.Now(),
			Enabled:   true,
		},
	)
}

// Evaluate evaluate all active strategies, return final decision
func (se *StrategyEngine) Evaluate(obs *Observation, profile *BehaviorSummary) *Decision {
	se.mu.RLock()
	defer se.mu.RUnlock()

	decision := &Decision{
		Action:      ActionAllow,
		ThreatClass: ThreatNone,
		Confidence:  1.0,
	}

	if profile != nil {
		decision.BehaviorSummary = profile
	}

	// Collect all triggered strategies, take highest priority Action
	var triggered []*Strategy
	for _, s := range se.strategies {
		if !s.Enabled {
			continue
		}
		if s.Condition(obs, profile) {
			triggered = append(triggered, s)
			s.HitCount++
		} else {
			s.MissCount++
		}
	}

	if len(triggered) == 0 {
		return decision
	}

	// Find highest priority strategy
	best := triggered[0]
	for _, s := range triggered[1:] {
		if s.Priority > best.Priority {
			best = s
		}
	}

	decision.Action = best.Action
	decision.ThreatClass = best.ThreatClass

	// Confidence = triggered strategy hit ratio (higher hit rate more reliable)
	if best.HitCount+best.MissCount > 0 {
		decision.Confidence = float64(best.HitCount) / float64(best.HitCount+best.MissCount)
	}

	for _, s := range triggered {
		decision.TriggeredStrategies = append(decision.TriggeredStrategies, s.ID)
		decision.Insights = append(decision.Insights, s.Description)
	}

	return decision
}

// Evolve strategy self-evolution — automatically generate new strategies or eliminate ineffective strategies based on accumulated observation statistics
func (se *StrategyEngine) Evolve() {
	se.mu.Lock()
	defer se.mu.Unlock()

	// 1. Eliminate learned strategies with no hits for extended period
	var kept []*Strategy
	for _, s := range se.strategies {
		if s.Learned && s.HitCount == 0 && s.MissCount > 100 {
			continue // eliminate
		}
		kept = append(kept, s)
	}
	se.strategies = kept

	// 2. Learn new patterns from observation statistics
	se.learnFromObservations()
}

// learnFromObservations learn new threat patterns from observation data
func (se *StrategyEngine) learnFromObservations() {
	sessions := se.memory.AllSessions()
	if len(sessions) < se.config.MinObservationsToLearn {
		return
	}

	// Statistics of global fingerprint switching frequency distribution
	var totalSwitchRate float64
	var sessionCount int

	for _, clientID := range sessions {
		session := se.memory.GetSession(clientID)
		if session == nil || len(session.Observations) < 3 {
			continue
		}
		// Simple switch rate calculation
		switches := 0
		obs := session.Observations
		for i := 1; i < len(obs); i++ {
			if obs[i].FingerprintHash != obs[i-1].FingerprintHash {
				switches++
			}
		}
		duration := obs[len(obs)-1].Timestamp.Sub(obs[0].Timestamp)
		if duration.Minutes() > 0 {
			totalSwitchRate += float64(switches) / duration.Minutes()
			sessionCount++
		}
	}

	if sessionCount == 0 {
		return
	}

	avgSwitchRate := totalSwitchRate / float64(sessionCount)

	// If global average switch rate far exceeds half of threshold, generate stricter strategy
	if avgSwitchRate > se.config.FPSwitchRateThreshold*0.5 {
		newThreshold := avgSwitchRate * 1.5
		strategyID := fmt.Sprintf("learned_adaptive_fp_switch_%d", se.learnedPatterns)

		// Check if similar strategy already exists
		for _, s := range se.strategies {
			if s.ThreatClass == ThreatFingerprintSpoof && s.Learned {
				return // already exists, skip
			}
		}

		se.strategies = append(se.strategies, &Strategy{
			ID:          strategyID,
			Name:        "Adaptive Fingerprint Switching Detection",
			Description: fmt.Sprintf("Based on observation learning: switch rate > %.1f/min considered anomaly (global mean %.1f/min)", newThreshold, avgSwitchRate),
			ThreatClass: ThreatFingerprintSpoof,
			Action:      ActionMonitor,
			Priority:    60,
			Condition: func(obs *Observation, profile *BehaviorSummary) bool {
				return profile.FPSwitchRate > newThreshold
			},
			CreatedAt: time.Now(),
			Learned:   true,
			Enabled:   true,
		})
		se.learnedPatterns++
	}
}

// ListActive return all active strategy summaries
func (se *StrategyEngine) ListActive() []StrategyInfo {
	se.mu.RLock()
	defer se.mu.RUnlock()

	var result []StrategyInfo
	for _, s := range se.strategies {
		if !s.Enabled {
			continue
		}
		result = append(result, StrategyInfo{
			ID:          s.ID,
			Name:        s.Name,
			Description: s.Description,
			ThreatClass: s.ThreatClass,
			Action:      s.Action,
			Priority:    s.Priority,
			HitCount:    s.HitCount,
			Learned:     s.Learned,
			Enabled:     s.Enabled,
		})
	}
	return result
}

// LearnedPatternCount return count of learned patterns
func (se *StrategyEngine) LearnedPatternCount() int {
	se.mu.RLock()
	defer se.mu.RUnlock()
	return se.learnedPatterns
}
