// Package gateway - HTML Response Injector with P3 Anti-Detection Code
// 自动拦截HTML响应并注入P3反检测代码
package gateway

import (
	"bytes"
	"fmt"
	"io"
	"net/http"
	"net/http/httputil"
	"net/url"
	"regexp"
	"strings"
	"sync"

	"github.com/vistone/fingerprint/modules/frontend"
	utils "github.com/vistone/fingerprint/modules/kit"
	"github.com/vistone/fingerprint/modules/profiles"
)

// 预编译 HTML 注入点匹配正则
var (
	injectorHeadPattern = regexp.MustCompile(`(?i)<head[^>]*>`)
	injectorHTMLPattern = regexp.MustCompile(`(?i)<html[^>]*>`)
)

func buildInjectionCode(cfg *InjectorConfig, generator *frontend.JSAntiDetectCodeGenerator) string {
	var buf bytes.Buffer

	if cfg.AddInjectionMarker {
		buf.WriteString("\n<!-- P3 Anti-Detection Injection Start -->\n")
	}

	buf.WriteString("<script>\n")
	buf.WriteString("// P3 Modern JS High-Entropy Anti-Detection Code\n")
	buf.WriteString("// Generated by fingerprint gateway\n")

	if generator != nil {
		antiDetectCode := generator.GenerateFullAntiDetectionCode()
		buf.WriteString(antiDetectCode)
		buf.WriteString("\n")
	}

	if cfg.InjectConsistency && generator != nil {
		buf.WriteString("\n// Cross-Layer Consistency Validation\n")
		consistencyCode := generator.GenerateCrossLayerConsistencyCode()
		buf.WriteString(consistencyCode)
		buf.WriteString("\n")
	}

	buf.WriteString("</script>\n")

	if cfg.AddInjectionMarker {
		buf.WriteString("<!-- P3 Anti-Detection Injection End -->\n")
	}

	return buf.String()
}

// InjectorConfig 注入器配置
type InjectorConfig struct {
	// 是否启用自动注入
	Enabled bool

	// 目标后端服务 URL（如果为空，则只拦截当前服务的响应）
	TargetURL string

	// 使用的 ClientProfile ID（用于生成反检测代码）
	ProfileID string

	// ClientProfile（如果提供，直接使用，否则从 ProfileID 加载）
	Profile *profiles.ClientProfile

	// 是否注入一致性校验代码
	InjectConsistency bool

	// 是否只在 <head> 标签存在时注入（否则注入到 <html> 后）
	RequireHeadTag bool

	// 是否添加注入标记注释
	AddInjectionMarker bool

	// 自定义注入位置（如果为空，默认在 <head> 后）
	CustomInjectionPoint string // 例如 "</title>" 表示在 title 标签后注入
}

// DefaultInjectorConfig 默认注入器配置
var DefaultInjectorConfig = &InjectorConfig{
	Enabled:              true,
	InjectConsistency:    true,
	RequireHeadTag:       true,
	AddInjectionMarker:   false,
	CustomInjectionPoint: "",
}

// HTMLInjector HTML 响应注入器
type HTMLInjector struct {
	config     *InjectorConfig
	profile    *profiles.ClientProfile
	generator  *frontend.JSAntiDetectCodeGenerator
	validator  *utils.ConsistencyValidator
	proxy      *httputil.ReverseProxy
	mu         sync.RWMutex
	codeCache  string // 缓存生成的代码
	cacheValid bool
}

// NewHTMLInjector 创建新的 HTML 注入器
func NewHTMLInjector(config *InjectorConfig) (*HTMLInjector, error) {
	if config == nil {
		config = DefaultInjectorConfig
	}

	injector := &HTMLInjector{
		config: config,
	}

	// 加载或使用提供的 Profile
	if config.Profile != nil {
		injector.profile = config.Profile
	} else if config.ProfileID != "" {
		// TODO: 从配置文件或数据库加载 profile
		// 这里暂时返回错误，需要用户提供 Profile
		return nil, fmt.Errorf("profile loading not implemented, please provide Profile directly")
	} else {
		// 使用默认空配置（不注入任何代码）
		injector.profile = &profiles.ClientProfile{}
	}

	// 初始化生成器
	if injector.profile.JSAntiDetection != nil {
		injector.generator = frontend.NewJSAntiDetectCodeGenerator(injector.profile)
		injector.validator = utils.NewConsistencyValidator(injector.profile)
	}

	// 如果提供了目标 URL，设置反向代理
	if config.TargetURL != "" {
		targetURL, err := url.Parse(config.TargetURL)
		if err != nil {
			return nil, fmt.Errorf("invalid target URL: %w", err)
		}
		injector.proxy = httputil.NewSingleHostReverseProxy(targetURL)
		injector.proxy.ModifyResponse = injector.modifyResponse
	}

	return injector, nil
}

// SetProfile 动态更新 Profile（会清空代码缓存）
func (inj *HTMLInjector) SetProfile(profile *profiles.ClientProfile) {
	inj.mu.Lock()
	defer inj.mu.Unlock()

	inj.profile = profile
	inj.cacheValid = false

	if profile.JSAntiDetection != nil {
		inj.generator = frontend.NewJSAntiDetectCodeGenerator(profile)
		inj.validator = utils.NewConsistencyValidator(profile)
	} else {
		inj.generator = nil
		inj.validator = nil
	}
}

// GenerateInjectionCode 生成要注入的完整代码
func (inj *HTMLInjector) GenerateInjectionCode() string {
	inj.mu.RLock()
	if inj.cacheValid {
		code := inj.codeCache
		inj.mu.RUnlock()
		return code
	}
	inj.mu.RUnlock()

	inj.mu.Lock()
	defer inj.mu.Unlock()

	// 再次检查（双重检查锁定）
	if inj.cacheValid {
		return inj.codeCache
	}

	inj.codeCache = buildInjectionCode(inj.config, inj.generator)
	inj.cacheValid = true

	return inj.codeCache
}

// GenerateInjectionCodeForProfile 生成指定 profile 的注入代码，不修改全局注入器状态。
func (inj *HTMLInjector) GenerateInjectionCodeForProfile(profile *profiles.ClientProfile) string {
	if profile == nil || profile.JSAntiDetection == nil {
		return ""
	}
	gen := frontend.NewJSAntiDetectCodeGenerator(profile)
	inj.mu.RLock()
	cfg := *inj.config
	inj.mu.RUnlock()
	return buildInjectionCode(&cfg, gen)
}

// InjectIntoHTML 将代码注入到 HTML 响应中
func (inj *HTMLInjector) InjectIntoHTML(htmlContent []byte) []byte {
	if !inj.config.Enabled {
		return htmlContent
	}

	if inj.generator == nil {
		// 没有配置反检测，直接返回原内容
		return htmlContent
	}

	content := string(htmlContent)
	injectionCode := inj.GenerateInjectionCode()

	var injectedContent string

	// 尝试自定义注入点
	if inj.config.CustomInjectionPoint != "" {
		pattern := regexp.MustCompile(regexp.QuoteMeta(inj.config.CustomInjectionPoint))
		if loc := pattern.FindStringIndex(content); loc != nil {
			// 在自定义位置注入
			injectedContent = content[:loc[1]] + "\n" + injectionCode + content[loc[1]:]
			return []byte(injectedContent)
		}
	}

	// 尝试在 <head> 标签后注入（最推荐）
	if loc := injectorHeadPattern.FindStringIndex(content); loc != nil {
		injectedContent = content[:loc[1]] + "\n" + injectionCode + content[loc[1]:]
		return []byte(injectedContent)
	}

	// 如果 RequireHeadTag = false，尝试在 <html> 后注入
	if !inj.config.RequireHeadTag {
		if loc := injectorHTMLPattern.FindStringIndex(content); loc != nil {
			injectedContent = content[:loc[1]] + "\n" + injectionCode + content[loc[1]:]
			return []byte(injectedContent)
		}
	}

	// 如果都没找到，在文档最开始注入（作为最后的备选）
	if !inj.config.RequireHeadTag {
		return []byte(injectionCode + content)
	}

	// 不符合注入条件，返回原内容
	return htmlContent
}

// maxInjectableBodySize 可注入的 HTML 响应体最大大小（10MB）
const maxInjectableBodySize = 10 * 1024 * 1024

// modifyResponse 修改反向代理的响应（用于代理模式）
func (inj *HTMLInjector) modifyResponse(resp *http.Response) error {
	// 只处理 HTML 响应
	contentType := resp.Header.Get("Content-Type")
	if !strings.Contains(strings.ToLower(contentType), "text/html") {
		return nil
	}

	// 限制读取大小，防止超大响应导致 OOM
	bodyBytes, err := io.ReadAll(io.LimitReader(resp.Body, maxInjectableBodySize))
	if err != nil {
		return err
	}
	resp.Body.Close()

	// 注入代码
	injectedBody := inj.InjectIntoHTML(bodyBytes)

	// 创建新的响应体
	resp.Body = io.NopCloser(bytes.NewReader(injectedBody))
	resp.Header.Set("Content-Length", fmt.Sprintf("%d", len(injectedBody)))

	// 移除可能的 Content-Encoding（因为我们已经解压并修改了内容）
	resp.Header.Del("Content-Encoding")

	return nil
}

// ServeHTTP 实现 http.Handler 接口（代理模式）
func (inj *HTMLInjector) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if inj.proxy == nil {
		http.Error(w, "proxy not configured", http.StatusInternalServerError)
		return
	}

	inj.proxy.ServeHTTP(w, r)
}

// WrapHandler 包装现有的 HTTP handler（中间件模式）
func (inj *HTMLInjector) WrapHandler(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// 创建响应拦截器
		recorder := &responseRecorderWithInjection{
			ResponseWriter: w,
			injector:       inj,
			statusCode:     http.StatusOK,
		}

		// 调用下一个 handler
		next.ServeHTTP(recorder, r)

		// 如果是 HTML 响应，注入代码
		if recorder.shouldInject() {
			injectedBody := inj.InjectIntoHTML(recorder.body.Bytes())
			w.Header().Set("Content-Length", fmt.Sprintf("%d", len(injectedBody)))
			w.WriteHeader(recorder.statusCode)
			w.Write(injectedBody)
		} else {
			// 否则直接写入原响应
			w.WriteHeader(recorder.statusCode)
			w.Write(recorder.body.Bytes())
		}
	})
}

// WrapHandlerFunc 包装 HandlerFunc（中间件模式）
func (inj *HTMLInjector) WrapHandlerFunc(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		// 创建响应拦截器
		recorder := &responseRecorderWithInjection{
			ResponseWriter: w,
			injector:       inj,
			statusCode:     http.StatusOK,
		}

		// 调用下一个 handler
		next(recorder, r)

		// 如果是 HTML 响应，注入代码
		if recorder.shouldInject() {
			injectedBody := inj.InjectIntoHTML(recorder.body.Bytes())
			w.Header().Set("Content-Length", fmt.Sprintf("%d", len(injectedBody)))
			w.WriteHeader(recorder.statusCode)
			w.Write(injectedBody)
		} else {
			// 否则直接写入原响应
			w.WriteHeader(recorder.statusCode)
			w.Write(recorder.body.Bytes())
		}
	}
}

// responseRecorderWithInjection 响应记录器（用于中间件模式）
type responseRecorderWithInjection struct {
	http.ResponseWriter
	injector    *HTMLInjector
	body        bytes.Buffer
	statusCode  int
	wroteHeader bool
}

func (rec *responseRecorderWithInjection) Write(b []byte) (int, error) {
	return rec.body.Write(b)
}

func (rec *responseRecorderWithInjection) WriteHeader(code int) {
	if !rec.wroteHeader {
		rec.statusCode = code
		rec.wroteHeader = true
	}
}

func (rec *responseRecorderWithInjection) shouldInject() bool {
	contentType := rec.Header().Get("Content-Type")
	return strings.Contains(strings.ToLower(contentType), "text/html")
}

// ProxyHandler 返回一个代理 handler（代理模式）
func (inj *HTMLInjector) ProxyHandler() http.Handler {
	return inj
}

// InjectorMiddleware 返回中间件函数（中间件模式）
func (inj *HTMLInjector) InjectorMiddleware(next http.Handler) http.Handler {
	return inj.WrapHandler(next)
}
