// Package gateway - HTML Response Injector with P3 Anti-Detection Code
// translated comment
package gateway

import (
	"bytes"
	"fmt"
	"io"
	"net/http"
	"net/http/httputil"
	"net/url"
	"regexp"
	"strings"
	"sync"

	"github.com/vistone/fingerprint/modules/frontend"
	utils "github.com/vistone/fingerprint/modules/kit"
	"github.com/vistone/fingerprint/modules/profiles"
)

// translated comment
var (
	injectorHeadPattern = regexp.MustCompile(`(?i)<head[^>]*>`)
	injectorHTMLPattern = regexp.MustCompile(`(?i)<html[^>]*>`)
)

func buildInjectionCode(cfg *InjectorConfig, generator *frontend.JSAntiDetectCodeGenerator) string {
	var buf bytes.Buffer

	if cfg.AddInjectionMarker {
		buf.WriteString("\n<!-- P3 Anti-Detection Injection Start -->\n")
	}

	buf.WriteString("<script>\n")
	buf.WriteString("// P3 Modern JS High-Entropy Anti-Detection Code\n")
	buf.WriteString("// Generated by fingerprint gateway\n")

	if generator != nil {
		antiDetectCode := generator.GenerateFullAntiDetectionCode()
		buf.WriteString(antiDetectCode)
		buf.WriteString("\n")
	}

	if cfg.InjectConsistency && generator != nil {
		buf.WriteString("\n// Cross-Layer Consistency Validation\n")
		consistencyCode := generator.GenerateCrossLayerConsistencyCode()
		buf.WriteString(consistencyCode)
		buf.WriteString("\n")
	}

	buf.WriteString("</script>\n")

	if cfg.AddInjectionMarker {
		buf.WriteString("<!-- P3 Anti-Detection Injection End -->\n")
	}

	return buf.String()
}

// translated comment
type InjectorConfig struct {
	// translated comment
	Enabled bool

	// translated comment
	TargetURL string

	// translated comment
	ProfileID string

	// translated comment
	Profile *profiles.ClientProfile

	// translated comment
	InjectConsistency bool

	// translated comment
	RequireHeadTag bool

	// translated comment
	AddInjectionMarker bool

	// translated comment
	CustomInjectionPoint string // translated comment
}

// translated comment
var DefaultInjectorConfig = &InjectorConfig{
	Enabled:              true,
	InjectConsistency:    true,
	RequireHeadTag:       true,
	AddInjectionMarker:   false,
	CustomInjectionPoint: "",
}

// translated comment
type HTMLInjector struct {
	config     *InjectorConfig
	profile    *profiles.ClientProfile
	generator  *frontend.JSAntiDetectCodeGenerator
	validator  *utils.ConsistencyValidator
	proxy      *httputil.ReverseProxy
	mu         sync.RWMutex
	codeCache  string // translated comment
	cacheValid bool
}

// translated comment
func NewHTMLInjector(config *InjectorConfig) (*HTMLInjector, error) {
	if config == nil {
		config = DefaultInjectorConfig
	}

	injector := &HTMLInjector{
		config: config,
	}

	// translated comment
	if config.Profile != nil {
		injector.profile = config.Profile
	} else if config.ProfileID != "" {
		// translated comment
		// translated comment
		return nil, fmt.Errorf("profile loading not implemented, please provide Profile directly")
	} else {
		// translated comment
		injector.profile = &profiles.ClientProfile{}
	}

	// translated comment
	if injector.profile.JSAntiDetection != nil {
		injector.generator = frontend.NewJSAntiDetectCodeGenerator(injector.profile)
		injector.validator = utils.NewConsistencyValidator(injector.profile)
	}

	// translated comment
	if config.TargetURL != "" {
		targetURL, err := url.Parse(config.TargetURL)
		if err != nil {
			return nil, fmt.Errorf("invalid target URL: %w", err)
		}
		injector.proxy = httputil.NewSingleHostReverseProxy(targetURL)
		injector.proxy.ModifyResponse = injector.modifyResponse
	}

	return injector, nil
}

// translated comment
func (inj *HTMLInjector) SetProfile(profile *profiles.ClientProfile) {
	inj.mu.Lock()
	defer inj.mu.Unlock()

	inj.profile = profile
	inj.cacheValid = false

	if profile.JSAntiDetection != nil {
		inj.generator = frontend.NewJSAntiDetectCodeGenerator(profile)
		inj.validator = utils.NewConsistencyValidator(profile)
	} else {
		inj.generator = nil
		inj.validator = nil
	}
}

// translated comment
func (inj *HTMLInjector) GenerateInjectionCode() string {
	inj.mu.RLock()
	if inj.cacheValid {
		code := inj.codeCache
		inj.mu.RUnlock()
		return code
	}
	inj.mu.RUnlock()

	inj.mu.Lock()
	defer inj.mu.Unlock()

	// translated comment
	if inj.cacheValid {
		return inj.codeCache
	}

	inj.codeCache = buildInjectionCode(inj.config, inj.generator)
	inj.cacheValid = true

	return inj.codeCache
}

// translated comment
func (inj *HTMLInjector) GenerateInjectionCodeForProfile(profile *profiles.ClientProfile) string {
	if profile == nil || profile.JSAntiDetection == nil {
		return ""
	}
	gen := frontend.NewJSAntiDetectCodeGenerator(profile)
	inj.mu.RLock()
	cfg := *inj.config
	inj.mu.RUnlock()
	return buildInjectionCode(&cfg, gen)
}

// translated comment
func (inj *HTMLInjector) InjectIntoHTML(htmlContent []byte) []byte {
	if !inj.config.Enabled {
		return htmlContent
	}

	if inj.generator == nil {
		// translated comment
		return htmlContent
	}

	content := string(htmlContent)
	injectionCode := inj.GenerateInjectionCode()

	var injectedContent string

	// translated comment
	if inj.config.CustomInjectionPoint != "" {
		pattern := regexp.MustCompile(regexp.QuoteMeta(inj.config.CustomInjectionPoint))
		if loc := pattern.FindStringIndex(content); loc != nil {
			// translated comment
			injectedContent = content[:loc[1]] + "\n" + injectionCode + content[loc[1]:]
			return []byte(injectedContent)
		}
	}

	// translated comment
	if loc := injectorHeadPattern.FindStringIndex(content); loc != nil {
		injectedContent = content[:loc[1]] + "\n" + injectionCode + content[loc[1]:]
		return []byte(injectedContent)
	}

	// translated comment
	if !inj.config.RequireHeadTag {
		if loc := injectorHTMLPattern.FindStringIndex(content); loc != nil {
			injectedContent = content[:loc[1]] + "\n" + injectionCode + content[loc[1]:]
			return []byte(injectedContent)
		}
	}

	// translated comment
	if !inj.config.RequireHeadTag {
		return []byte(injectionCode + content)
	}

	// translated comment
	return htmlContent
}

// translated comment
const maxInjectableBodySize = 10 * 1024 * 1024

// translated comment
func (inj *HTMLInjector) modifyResponse(resp *http.Response) error {
	// translated comment
	contentType := resp.Header.Get("Content-Type")
	if !strings.Contains(strings.ToLower(contentType), "text/html") {
		return nil
	}

	// translated comment
	bodyBytes, err := io.ReadAll(io.LimitReader(resp.Body, maxInjectableBodySize))
	if err != nil {
		return err
	}
	resp.Body.Close()

	// translated comment
	injectedBody := inj.InjectIntoHTML(bodyBytes)

	// translated comment
	resp.Body = io.NopCloser(bytes.NewReader(injectedBody))
	resp.Header.Set("Content-Length", fmt.Sprintf("%d", len(injectedBody)))

	// translated comment
	resp.Header.Del("Content-Encoding")

	return nil
}

// translated comment
func (inj *HTMLInjector) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if inj.proxy == nil {
		http.Error(w, "proxy not configured", http.StatusInternalServerError)
		return
	}

	inj.proxy.ServeHTTP(w, r)
}

// translated comment
func (inj *HTMLInjector) WrapHandler(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// translated comment
		recorder := &responseRecorderWithInjection{
			ResponseWriter: w,
			injector:       inj,
			statusCode:     http.StatusOK,
		}

		// translated comment
		next.ServeHTTP(recorder, r)

		// translated comment
		if recorder.shouldInject() {
			injectedBody := inj.InjectIntoHTML(recorder.body.Bytes())
			w.Header().Set("Content-Length", fmt.Sprintf("%d", len(injectedBody)))
			w.WriteHeader(recorder.statusCode)
			w.Write(injectedBody)
		} else {
			// translated comment
			w.WriteHeader(recorder.statusCode)
			w.Write(recorder.body.Bytes())
		}
	})
}

// translated comment
func (inj *HTMLInjector) WrapHandlerFunc(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		// translated comment
		recorder := &responseRecorderWithInjection{
			ResponseWriter: w,
			injector:       inj,
			statusCode:     http.StatusOK,
		}

		// translated comment
		next(recorder, r)

		// translated comment
		if recorder.shouldInject() {
			injectedBody := inj.InjectIntoHTML(recorder.body.Bytes())
			w.Header().Set("Content-Length", fmt.Sprintf("%d", len(injectedBody)))
			w.WriteHeader(recorder.statusCode)
			w.Write(injectedBody)
		} else {
			// translated comment
			w.WriteHeader(recorder.statusCode)
			w.Write(recorder.body.Bytes())
		}
	}
}

// translated comment
type responseRecorderWithInjection struct {
	http.ResponseWriter
	injector    *HTMLInjector
	body        bytes.Buffer
	statusCode  int
	wroteHeader bool
}

func (rec *responseRecorderWithInjection) Write(b []byte) (int, error) {
	return rec.body.Write(b)
}

func (rec *responseRecorderWithInjection) WriteHeader(code int) {
	if !rec.wroteHeader {
		rec.statusCode = code
		rec.wroteHeader = true
	}
}

func (rec *responseRecorderWithInjection) shouldInject() bool {
	contentType := rec.Header().Get("Content-Type")
	return strings.Contains(strings.ToLower(contentType), "text/html")
}

// translated comment
func (inj *HTMLInjector) ProxyHandler() http.Handler {
	return inj
}

// translated comment
func (inj *HTMLInjector) InjectorMiddleware(next http.Handler) http.Handler {
	return inj.WrapHandler(next)
}
