// Package gateway - HTML Response Injector with Anti-Detection Code
// Automatically intercepts HTML responses and injects anti-detection code
package gateway

import (
	"bytes"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/http/httputil"
	"net/url"
	"regexp"
	"strings"
	"sync"

	"github.com/vistone/fingerprint/modules/frontend"
	utils "github.com/vistone/fingerprint/modules/kit"
	"github.com/vistone/fingerprint/modules/profiles"
)

// Pre-compiled HTML injection point regex patterns
var (
	injectorHeadPattern = regexp.MustCompile(`(?i)<head[^>]*>`)
	injectorHTMLPattern = regexp.MustCompile(`(?i)<html[^>]*>`)
)

// validateProxyTarget checks that the target URL does not point to internal
// or loopback addresses to prevent SSRF attacks.
// Set allowPrivate=true for Docker/Kubernetes environments where internal
// service names resolve to private IPs.
func validateProxyTarget(targetURL *url.URL, allowPrivate bool) error {
	host := targetURL.Hostname()
	if host == "" {
		return fmt.Errorf("proxy target URL has empty host")
	}

	// Reject common loopback/metadata hostnames
	lower := strings.ToLower(host)
	if lower == "localhost" || lower == "metadata.google.internal" {
		return fmt.Errorf("proxy target %q is a restricted hostname", host)
	}

	// Resolve and check IP ranges
	ips, err := net.LookupHost(host)
	if err != nil {
		// DNS resolution failure is not fatal; the proxy will fail at request time.
		return nil
	}

	for _, ipStr := range ips {
		ip := net.ParseIP(ipStr)
		if ip == nil {
			continue
		}
		// Always block loopback, link-local, and unspecified
		if ip.IsLoopback() || ip.IsLinkLocalUnicast() || ip.IsLinkLocalMulticast() || ip.IsUnspecified() {
			return fmt.Errorf("proxy target %q resolves to restricted address %s", host, ipStr)
		}
		// Block RFC 1918 / RFC 6598 private ranges unless explicitly allowed
		if !allowPrivate {
			if ip4 := ip.To4(); ip4 != nil {
				if ip4[0] == 10 ||
					(ip4[0] == 172 && ip4[1] >= 16 && ip4[1] <= 31) ||
					(ip4[0] == 192 && ip4[1] == 168) ||
					(ip4[0] == 100 && ip4[1] >= 64 && ip4[1] <= 127) ||
					(ip4[0] == 169 && ip4[1] == 254) {
					return fmt.Errorf("proxy target %q resolves to private address %s", host, ipStr)
				}
			}
		}
	}

	return nil
}

func buildInjectionCode(cfg *InjectorConfig, generator *frontend.JSAntiDetectCodeGenerator) string {
	var buf bytes.Buffer

	if cfg.AddInjectionMarker {
		buf.WriteString("\n<!-- Anti-Detection Injection Start -->\n")
	}

	buf.WriteString("<script>\n")
	buf.WriteString("// Modern JS High-Entropy Anti-Detection Code\n")
	buf.WriteString("// Generated by fingerprint gateway\n")

	if generator != nil {
		antiDetectCode := generator.GenerateFullAntiDetectionCode()
		buf.WriteString(antiDetectCode)
		buf.WriteString("\n")
	}

	if cfg.InjectConsistency && generator != nil {
		buf.WriteString("\n// Cross-Layer Consistency Validation\n")
		consistencyCode := generator.GenerateCrossLayerConsistencyCode()
		buf.WriteString(consistencyCode)
		buf.WriteString("\n")
	}

	buf.WriteString("</script>\n")

	if cfg.AddInjectionMarker {
		buf.WriteString("<!-- Anti-Detection Injection End -->\n")
	}

	return buf.String()
}

// InjectorConfig injector configuration
type InjectorConfig struct {
	// Whether to enable automatic injection
	Enabled bool

	// Target backend service URL (if empty, only intercept current service responses)
	TargetURL string

	// ClientProfile ID to use (for generating anti-detection code)
	ProfileID string

	// ClientProfile (if provided, use directly; otherwise load from ProfileID)
	Profile *profiles.ClientProfile

	// Whether to inject consistency validation code
	InjectConsistency bool

	// Whether to only inject when <head> tag exists (otherwise inject after <html>)
	RequireHeadTag bool

	// Whether to add injection marker comments
	AddInjectionMarker bool

	// Custom injection point (if empty, default is after <head>)
	CustomInjectionPoint string // e.g. "</title>" means inject after title tag

	// AllowPrivateTarget permits proxy targets that resolve to RFC 1918 private
	// addresses. Enable this when running inside Docker/Kubernetes where services
	// communicate over internal networks.
	AllowPrivateTarget bool
}

// DefaultInjectorConfig default injector configuration
var DefaultInjectorConfig = &InjectorConfig{
	Enabled:              true,
	InjectConsistency:    true,
	RequireHeadTag:       true,
	AddInjectionMarker:   false,
	CustomInjectionPoint: "",
	AllowPrivateTarget:   false,
}

// HTMLInjector HTML response injector
type HTMLInjector struct {
	config     *InjectorConfig
	profile    *profiles.ClientProfile
	generator  *frontend.JSAntiDetectCodeGenerator
	validator  *utils.ConsistencyValidator
	proxy      *httputil.ReverseProxy
	mu         sync.RWMutex
	codeCache  string // Cache for generated code
	cacheValid bool   // Whether cache is valid
}

// NewHTMLInjector creates a new HTML injector
func NewHTMLInjector(config *InjectorConfig) (*HTMLInjector, error) {
	if config == nil {
		config = DefaultInjectorConfig
	}

	injector := &HTMLInjector{
		config: config,
	}

	// Load or use provided Profile
	if config.Profile != nil {
		injector.profile = config.Profile
	} else if config.ProfileID != "" {
		// TODO: Load profile from config file or database
		// Return error for now, user needs to provide Profile
		return nil, fmt.Errorf("profile loading not implemented, please provide Profile directly")
	} else {
		// Use default empty config (no code injection)
		injector.profile = &profiles.ClientProfile{}
	}

	// Initialize generator
	if injector.profile.JSAntiDetection != nil {
		injector.generator = frontend.NewJSAntiDetectCodeGenerator(injector.profile)
		injector.validator = utils.NewConsistencyValidator(injector.profile)
	}

	// If target URL is provided, set up reverse proxy with SSRF protection
	if config.TargetURL != "" {
		targetURL, err := url.Parse(config.TargetURL)
		if err != nil {
			return nil, fmt.Errorf("invalid target URL: %w", err)
		}
		if err := validateProxyTarget(targetURL, config.AllowPrivateTarget); err != nil {
			return nil, fmt.Errorf("proxy target rejected: %w", err)
		}
		injector.proxy = httputil.NewSingleHostReverseProxy(targetURL)
		injector.proxy.ModifyResponse = injector.modifyResponse
	}

	return injector, nil
}

// SetProfile dynamically updates the Profile and invalidates the code cache.
func (inj *HTMLInjector) SetProfile(profile *profiles.ClientProfile) {
	inj.mu.Lock()
	defer inj.mu.Unlock()

	inj.profile = profile
	inj.cacheValid = false

	if profile.JSAntiDetection != nil {
		inj.generator = frontend.NewJSAntiDetectCodeGenerator(profile)
		inj.validator = utils.NewConsistencyValidator(profile)
	} else {
		inj.generator = nil
		inj.validator = nil
	}
}

// GenerateInjectionCode generates the full anti-detection code to inject.
func (inj *HTMLInjector) GenerateInjectionCode() string {
	inj.mu.RLock()
	if inj.cacheValid {
		code := inj.codeCache
		inj.mu.RUnlock()
		return code
	}
	inj.mu.RUnlock()

	inj.mu.Lock()
	defer inj.mu.Unlock()

	// Double-checked locking
	if inj.cacheValid {
		return inj.codeCache
	}

	inj.codeCache = buildInjectionCode(inj.config, inj.generator)
	inj.cacheValid = true

	return inj.codeCache
}

// GenerateInjectionCodeForProfile generates injection code for the given profile without modifying global state.
func (inj *HTMLInjector) GenerateInjectionCodeForProfile(profile *profiles.ClientProfile) string {
	if profile == nil || profile.JSAntiDetection == nil {
		return ""
	}
	gen := frontend.NewJSAntiDetectCodeGenerator(profile)
	inj.mu.RLock()
	cfg := *inj.config
	inj.mu.RUnlock()
	return buildInjectionCode(&cfg, gen)
}

// InjectIntoHTML injects anti-detection code into an HTML response body.
func (inj *HTMLInjector) InjectIntoHTML(htmlContent []byte) []byte {
	if !inj.config.Enabled {
		return htmlContent
	}

	if inj.generator == nil {
		// No anti-detection configured, return original content
		return htmlContent
	}

	content := string(htmlContent)
	injectionCode := inj.GenerateInjectionCode()

	var injectedContent string

	// Try custom injection point (use simple string search instead of regexp on hot path)
	if inj.config.CustomInjectionPoint != "" {
		if idx := strings.Index(content, inj.config.CustomInjectionPoint); idx >= 0 {
			end := idx + len(inj.config.CustomInjectionPoint)
			injectedContent = content[:end] + "\n" + injectionCode + content[end:]
			return []byte(injectedContent)
		}
	}

	// Try injecting after <head> tag (preferred)
	if loc := injectorHeadPattern.FindStringIndex(content); loc != nil {
		injectedContent = content[:loc[1]] + "\n" + injectionCode + content[loc[1]:]
		return []byte(injectedContent)
	}

	// If RequireHeadTag is false, try injecting after <html>
	if !inj.config.RequireHeadTag {
		if loc := injectorHTMLPattern.FindStringIndex(content); loc != nil {
			injectedContent = content[:loc[1]] + "\n" + injectionCode + content[loc[1]:]
			return []byte(injectedContent)
		}
	}

	// Fallback: inject at the beginning of the document
	if !inj.config.RequireHeadTag {
		return []byte(injectionCode + content)
	}

	// Does not meet injection criteria, return original content
	return htmlContent
}

// maxInjectableBodySize is the maximum HTML response body size for injection (10MB).
const maxInjectableBodySize = 10 * 1024 * 1024

// modifyResponse modifies reverse proxy responses (proxy mode).
func (inj *HTMLInjector) modifyResponse(resp *http.Response) error {
	// Only process HTML responses
	contentType := resp.Header.Get("Content-Type")
	if !strings.Contains(strings.ToLower(contentType), "text/html") {
		return nil
	}

	// Limit read size to prevent OOM from oversized responses
	bodyBytes, err := io.ReadAll(io.LimitReader(resp.Body, maxInjectableBodySize))
	if err != nil {
		return err
	}
	resp.Body.Close()

	// Inject code
	injectedBody := inj.InjectIntoHTML(bodyBytes)

	// Build new response body
	resp.Body = io.NopCloser(bytes.NewReader(injectedBody))
	resp.Header.Set("Content-Length", fmt.Sprintf("%d", len(injectedBody)))

	// Remove Content-Encoding since we decompressed and modified the body
	resp.Header.Del("Content-Encoding")

	return nil
}

// ServeHTTP implements http.Handler (proxy mode).
func (inj *HTMLInjector) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if inj.proxy == nil {
		http.Error(w, "proxy not configured", http.StatusInternalServerError)
		return
	}

	inj.proxy.ServeHTTP(w, r)
}

// WrapHandler wraps an existing HTTP handler (middleware mode).
func (inj *HTMLInjector) WrapHandler(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// Create response interceptor
		recorder := &responseRecorderWithInjection{
			ResponseWriter: w,
			injector:       inj,
			statusCode:     http.StatusOK,
		}

		// Call next handler
		next.ServeHTTP(recorder, r)

		// Inject code if the response is HTML
		if recorder.shouldInject() {
			injectedBody := inj.InjectIntoHTML(recorder.body.Bytes())
			w.Header().Set("Content-Length", fmt.Sprintf("%d", len(injectedBody)))
			w.WriteHeader(recorder.statusCode)
			w.Write(injectedBody)
		} else {
			// Write original response as-is
			w.WriteHeader(recorder.statusCode)
			w.Write(recorder.body.Bytes())
		}
	})
}

// WrapHandlerFunc wraps an http.HandlerFunc (middleware mode).
func (inj *HTMLInjector) WrapHandlerFunc(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		// Create response interceptor
		recorder := &responseRecorderWithInjection{
			ResponseWriter: w,
			injector:       inj,
			statusCode:     http.StatusOK,
		}

		// Call next handler
		next(recorder, r)

		// Inject code if the response is HTML
		if recorder.shouldInject() {
			injectedBody := inj.InjectIntoHTML(recorder.body.Bytes())
			w.Header().Set("Content-Length", fmt.Sprintf("%d", len(injectedBody)))
			w.WriteHeader(recorder.statusCode)
			w.Write(injectedBody)
		} else {
			// Write original response as-is
			w.WriteHeader(recorder.statusCode)
			w.Write(recorder.body.Bytes())
		}
	}
}

// responseRecorderWithInjection is a response recorder for middleware mode.
type responseRecorderWithInjection struct {
	http.ResponseWriter
	injector    *HTMLInjector
	body        bytes.Buffer
	statusCode  int
	wroteHeader bool
}

func (rec *responseRecorderWithInjection) Write(b []byte) (int, error) {
	return rec.body.Write(b)
}

func (rec *responseRecorderWithInjection) WriteHeader(code int) {
	if !rec.wroteHeader {
		rec.statusCode = code
		rec.wroteHeader = true
	}
}

func (rec *responseRecorderWithInjection) shouldInject() bool {
	contentType := rec.Header().Get("Content-Type")
	return strings.Contains(strings.ToLower(contentType), "text/html")
}

// ProxyHandler returns a proxy handler (proxy mode).
func (inj *HTMLInjector) ProxyHandler() http.Handler {
	return inj
}

// InjectorMiddleware returns a middleware handler (middleware mode).
func (inj *HTMLInjector) InjectorMiddleware(next http.Handler) http.Handler {
	return inj.WrapHandler(next)
}
