// Code generated by cmd/profilegen; DO NOT EDIT.
// Generated at: 2026-03-03T10:44:26+08:00
// Source files: chrome_133.yaml

package profiles

import (
	"github.com/bogdanfinn/fhttp/http2"
	tls "github.com/bogdanfinn/utls"
)

func init() {
	// 注册所有生成的指纹配置
	registerGeneratedProfile("chrome_133", Chrome_133)
}


// Chrome_133 是 Chrome 133 的指纹配置（代码生成）
var Chrome_133 = ClientProfile{
	clientHelloId: tls.ClientHelloID{
		Client:               "Chrome",
		RandomExtensionOrder: false,
		Version:              "133",
		Seed:                 nil,
		SpecFactory:          Chrome_133SpecFactory,
	},
	settings: map[http2.SettingID]uint32{
		http2.SettingEnablePush: 0,
		http2.SettingHeaderTableSize: 65536,
		http2.SettingInitialWindowSize: 6291456,
		http2.SettingMaxHeaderListSize: 262144,
	},
	settingsOrder: []http2.SettingID{
		http2.SettingHeaderTableSize,
		http2.SettingEnablePush,
		http2.SettingInitialWindowSize,
		http2.SettingMaxHeaderListSize,
	},
	pseudoHeaderOrder: []string{
		":method",
		":authority",
		":scheme",
		":path",
	},
	connectionFlow: 15663105,
}

// Chrome_133SpecFactory 创建 Chrome 133 的 TLS ClientHello 规范
func Chrome_133SpecFactory() (tls.ClientHelloSpec, error) {
	return tls.ClientHelloSpec{
		CipherSuites: []uint16{
			tls.GREASE_PLACEHOLDER,
			tls.TLS_AES_128_GCM_SHA256,
			tls.TLS_AES_256_GCM_SHA384,
			tls.TLS_CHACHA20_POLY1305_SHA256,
			tls.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
			tls.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
			tls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
			tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
			tls.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,
			tls.TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,
			tls.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,
			tls.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,
			tls.TLS_RSA_WITH_AES_128_GCM_SHA256,
			tls.TLS_RSA_WITH_AES_256_GCM_SHA384,
			tls.TLS_RSA_WITH_AES_128_CBC_SHA,
			tls.TLS_RSA_WITH_AES_256_CBC_SHA,
		},
		CompressionMethods: []byte{
			tls.CompressionNone,
		},
		Extensions: []tls.TLSExtension{
			&tls.UtlsGREASEExtension{},
			&tls.SessionTicketExtension{},
			&tls.SignatureAlgorithmsExtension{SupportedSignatureAlgorithms: []tls.SignatureScheme{tls.tls.ECDSAWithP256AndSHA256, tls.tls.PSSWithSHA256, tls.tls.PKCS1WithSHA256, tls.tls.ECDSAWithP384AndSHA384, tls.tls.PSSWithSHA384, tls.tls.PKCS1WithSHA384, tls.tls.PSSWithSHA512, tls.tls.PKCS1WithSHA512}},
			&tls.ApplicationSettingsExtensionNew{SupportedProtocols: []string{"h3", "h2"}},
			&tls.KeyShareExtension{KeyShares: []tls.KeyShare{{Group: tls.tls.GREASE_PLACEHOLDER, Data: []byte{0}}, {Group: tls.tls.X25519MLKEM768}, {Group: tls.tls.X25519}}},
			&tls.SCTExtension{},
			&tls.SupportedPointsExtension{SupportedPoints: []byte{tls.tls.PointFormatUncompressed}},
			&tls.SupportedVersionsExtension{Versions: []uint16{tls.tls.GREASE_PLACEHOLDER, tls.tls.VersionTLS13, tls.tls.VersionTLS12}},
			&tls.StatusRequestExtension{},
			&tls.ALPNExtension{AlpnProtocols: []string{"h3", "h2", "http/1.1"}},
			&tls.SNIExtension{},
			tls.BoringGREASEECH(),
			&tls.UtlsCompressCertExtension{Algorithms: []tls.CertCompressionAlgo{tls.tls.CertCompressionBrotli}},
			&tls.SupportedCurvesExtension{Curves: []tls.CurveID{tls.tls.GREASE_PLACEHOLDER, tls.tls.X25519MLKEM768, tls.tls.X25519, tls.tls.CurveP256, tls.tls.CurveP384}},
			&tls.PSKKeyExchangeModesExtension{Modes: []uint8{tls.tls.PskModeDHE}},
			&tls.ExtendedMasterSecretExtension{},
			&tls.RenegotiationInfoExtension{Renegotiation: tls.tls.RenegotiateOnceAsClient},
			&tls.UtlsGREASEExtension{},
		},
	}, nil
}

