// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: modules/gateway/proto/fingerprint/v1/gateway.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClientId        string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	TlsVersion      uint32                 `protobuf:"varint,2,opt,name=tls_version,json=tlsVersion,proto3" json:"tls_version,omitempty"`
	CipherSuites    []uint32               `protobuf:"varint,3,rep,packed,name=cipher_suites,json=cipherSuites,proto3" json:"cipher_suites,omitempty"`
	Extensions      []uint32               `protobuf:"varint,4,rep,packed,name=extensions,proto3" json:"extensions,omitempty"`
	SupportedCurves []uint32               `protobuf:"varint,5,rep,packed,name=supported_curves,json=supportedCurves,proto3" json:"supported_curves,omitempty"`
	Headers         map[string]string      `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ClientIp        string                 `protobuf:"bytes,7,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AnalyzeRequest) Reset() {
	*x = AnalyzeRequest{}
	mi := &file_modules_gateway_proto_fingerprint_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeRequest) ProtoMessage() {}

func (x *AnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modules_gateway_proto_fingerprint_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_modules_gateway_proto_fingerprint_v1_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AnalyzeRequest) GetTlsVersion() uint32 {
	if x != nil {
		return x.TlsVersion
	}
	return 0
}

func (x *AnalyzeRequest) GetCipherSuites() []uint32 {
	if x != nil {
		return x.CipherSuites
	}
	return nil
}

func (x *AnalyzeRequest) GetExtensions() []uint32 {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *AnalyzeRequest) GetSupportedCurves() []uint32 {
	if x != nil {
		return x.SupportedCurves
	}
	return nil
}

func (x *AnalyzeRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *AnalyzeRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

type AnalyzeResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FingerprintHash  string                 `protobuf:"bytes,1,opt,name=fingerprint_hash,json=fingerprintHash,proto3" json:"fingerprint_hash,omitempty"`
	Protocol         string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	BrowserFamily    string                 `protobuf:"bytes,3,opt,name=browser_family,json=browserFamily,proto3" json:"browser_family,omitempty"`
	BrowserVersion   string                 `protobuf:"bytes,4,opt,name=browser_version,json=browserVersion,proto3" json:"browser_version,omitempty"`
	Confidence       float64                `protobuf:"fixed64,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	RiskLevel        string                 `protobuf:"bytes,6,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`
	RiskScore        float64                `protobuf:"fixed64,7,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	Ja3Hash          string                 `protobuf:"bytes,8,opt,name=ja3_hash,json=ja3Hash,proto3" json:"ja3_hash,omitempty"`
	Ja4Fingerprint   string                 `protobuf:"bytes,9,opt,name=ja4_fingerprint,json=ja4Fingerprint,proto3" json:"ja4_fingerprint,omitempty"`
	DefenseHints     []string               `protobuf:"bytes,10,rep,name=defense_hints,json=defenseHints,proto3" json:"defense_hints,omitempty"`
	Cached           bool                   `protobuf:"varint,11,opt,name=cached,proto3" json:"cached,omitempty"`
	ProcessingTimeMs int64                  `protobuf:"varint,12,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AnalyzeResponse) Reset() {
	*x = AnalyzeResponse{}
	mi := &file_modules_gateway_proto_fingerprint_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeResponse) ProtoMessage() {}

func (x *AnalyzeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modules_gateway_proto_fingerprint_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeResponse) Descriptor() ([]byte, []int) {
	return file_modules_gateway_proto_fingerprint_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeResponse) GetFingerprintHash() string {
	if x != nil {
		return x.FingerprintHash
	}
	return ""
}

func (x *AnalyzeResponse) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *AnalyzeResponse) GetBrowserFamily() string {
	if x != nil {
		return x.BrowserFamily
	}
	return ""
}

func (x *AnalyzeResponse) GetBrowserVersion() string {
	if x != nil {
		return x.BrowserVersion
	}
	return ""
}

func (x *AnalyzeResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *AnalyzeResponse) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *AnalyzeResponse) GetRiskScore() float64 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *AnalyzeResponse) GetJa3Hash() string {
	if x != nil {
		return x.Ja3Hash
	}
	return ""
}

func (x *AnalyzeResponse) GetJa4Fingerprint() string {
	if x != nil {
		return x.Ja4Fingerprint
	}
	return ""
}

func (x *AnalyzeResponse) GetDefenseHints() []string {
	if x != nil {
		return x.DefenseHints
	}
	return nil
}

func (x *AnalyzeResponse) GetCached() bool {
	if x != nil {
		return x.Cached
	}
	return false
}

func (x *AnalyzeResponse) GetProcessingTimeMs() int64 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_modules_gateway_proto_fingerprint_v1_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modules_gateway_proto_fingerprint_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_modules_gateway_proto_fingerprint_v1_gateway_proto_rawDescGZIP(), []int{2}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_modules_gateway_proto_fingerprint_v1_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modules_gateway_proto_fingerprint_v1_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_modules_gateway_proto_fingerprint_v1_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

var File_modules_gateway_proto_fingerprint_v1_gateway_proto protoreflect.FileDescriptor

const file_modules_gateway_proto_fingerprint_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"2modules/gateway/proto/fingerprint/v1/gateway.proto\x12\x16fingerprint.gateway.v1\"\xe6\x02\n" +
	"\x0eAnalyzeRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1f\n" +
	"\vtls_version\x18\x02 \x01(\rR\n" +
	"tlsVersion\x12#\n" +
	"\rcipher_suites\x18\x03 \x03(\rR\fcipherSuites\x12\x1e\n" +
	"\n" +
	"extensions\x18\x04 \x03(\rR\n" +
	"extensions\x12)\n" +
	"\x10supported_curves\x18\x05 \x03(\rR\x0fsupportedCurves\x12M\n" +
	"\aheaders\x18\x06 \x03(\v23.fingerprint.gateway.v1.AnalyzeRequest.HeadersEntryR\aheaders\x12\x1b\n" +
	"\tclient_ip\x18\a \x01(\tR\bclientIp\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb5\x03\n" +
	"\x0fAnalyzeResponse\x12)\n" +
	"\x10fingerprint_hash\x18\x01 \x01(\tR\x0ffingerprintHash\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12%\n" +
	"\x0ebrowser_family\x18\x03 \x01(\tR\rbrowserFamily\x12'\n" +
	"\x0fbrowser_version\x18\x04 \x01(\tR\x0ebrowserVersion\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x01R\n" +
	"confidence\x12\x1d\n" +
	"\n" +
	"risk_level\x18\x06 \x01(\tR\triskLevel\x12\x1d\n" +
	"\n" +
	"risk_score\x18\a \x01(\x01R\triskScore\x12\x19\n" +
	"\bja3_hash\x18\b \x01(\tR\aja3Hash\x12'\n" +
	"\x0fja4_fingerprint\x18\t \x01(\tR\x0eja4Fingerprint\x12#\n" +
	"\rdefense_hints\x18\n" +
	" \x03(\tR\fdefenseHints\x12\x16\n" +
	"\x06cached\x18\v \x01(\bR\x06cached\x12,\n" +
	"\x12processing_time_ms\x18\f \x01(\x03R\x10processingTimeMs\"\x0f\n" +
	"\rHealthRequest\"B\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice2\xc9\x01\n" +
	"\x12FingerprintGateway\x12Z\n" +
	"\aAnalyze\x12&.fingerprint.gateway.v1.AnalyzeRequest\x1a'.fingerprint.gateway.v1.AnalyzeResponse\x12W\n" +
	"\x06Health\x12%.fingerprint.gateway.v1.HealthRequest\x1a&.fingerprint.gateway.v1.HealthResponseBOZMgithub.com/vistone/fingerprint/modules/gateway/proto/fingerprint/v1;gatewayv1b\x06proto3"

var (
	file_modules_gateway_proto_fingerprint_v1_gateway_proto_rawDescOnce sync.Once
	file_modules_gateway_proto_fingerprint_v1_gateway_proto_rawDescData []byte
)

func file_modules_gateway_proto_fingerprint_v1_gateway_proto_rawDescGZIP() []byte {
	file_modules_gateway_proto_fingerprint_v1_gateway_proto_rawDescOnce.Do(func() {
		file_modules_gateway_proto_fingerprint_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_modules_gateway_proto_fingerprint_v1_gateway_proto_rawDesc), len(file_modules_gateway_proto_fingerprint_v1_gateway_proto_rawDesc)))
	})
	return file_modules_gateway_proto_fingerprint_v1_gateway_proto_rawDescData
}

var file_modules_gateway_proto_fingerprint_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_modules_gateway_proto_fingerprint_v1_gateway_proto_goTypes = []any{
	(*AnalyzeRequest)(nil),  // 0: fingerprint.gateway.v1.AnalyzeRequest
	(*AnalyzeResponse)(nil), // 1: fingerprint.gateway.v1.AnalyzeResponse
	(*HealthRequest)(nil),   // 2: fingerprint.gateway.v1.HealthRequest
	(*HealthResponse)(nil),  // 3: fingerprint.gateway.v1.HealthResponse
	nil,                     // 4: fingerprint.gateway.v1.AnalyzeRequest.HeadersEntry
}
var file_modules_gateway_proto_fingerprint_v1_gateway_proto_depIdxs = []int32{
	4, // 0: fingerprint.gateway.v1.AnalyzeRequest.headers:type_name -> fingerprint.gateway.v1.AnalyzeRequest.HeadersEntry
	0, // 1: fingerprint.gateway.v1.FingerprintGateway.Analyze:input_type -> fingerprint.gateway.v1.AnalyzeRequest
	2, // 2: fingerprint.gateway.v1.FingerprintGateway.Health:input_type -> fingerprint.gateway.v1.HealthRequest
	1, // 3: fingerprint.gateway.v1.FingerprintGateway.Analyze:output_type -> fingerprint.gateway.v1.AnalyzeResponse
	3, // 4: fingerprint.gateway.v1.FingerprintGateway.Health:output_type -> fingerprint.gateway.v1.HealthResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_modules_gateway_proto_fingerprint_v1_gateway_proto_init() }
func file_modules_gateway_proto_fingerprint_v1_gateway_proto_init() {
	if File_modules_gateway_proto_fingerprint_v1_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modules_gateway_proto_fingerprint_v1_gateway_proto_rawDesc), len(file_modules_gateway_proto_fingerprint_v1_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modules_gateway_proto_fingerprint_v1_gateway_proto_goTypes,
		DependencyIndexes: file_modules_gateway_proto_fingerprint_v1_gateway_proto_depIdxs,
		MessageInfos:      file_modules_gateway_proto_fingerprint_v1_gateway_proto_msgTypes,
	}.Build()
	File_modules_gateway_proto_fingerprint_v1_gateway_proto = out.File
	file_modules_gateway_proto_fingerprint_v1_gateway_proto_goTypes = nil
	file_modules_gateway_proto_fingerprint_v1_gateway_proto_depIdxs = nil
}
