// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: modules/gateway/proto/fingerprint/v1/gateway.proto

package gatewayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FingerprintGateway_Analyze_FullMethodName = "/fingerprint.gateway.v1.FingerprintGateway/Analyze"
	FingerprintGateway_Health_FullMethodName  = "/fingerprint.gateway.v1.FingerprintGateway/Health"
)

// FingerprintGatewayClient is the client API for FingerprintGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FingerprintGatewayClient interface {
	Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type fingerprintGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewFingerprintGatewayClient(cc grpc.ClientConnInterface) FingerprintGatewayClient {
	return &fingerprintGatewayClient{cc}
}

func (c *fingerprintGatewayClient) Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, FingerprintGateway_Analyze_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fingerprintGatewayClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, FingerprintGateway_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FingerprintGatewayServer is the server API for FingerprintGateway service.
// All implementations must embed UnimplementedFingerprintGatewayServer
// for forward compatibility.
type FingerprintGatewayServer interface {
	Analyze(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedFingerprintGatewayServer()
}

// UnimplementedFingerprintGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFingerprintGatewayServer struct{}

func (UnimplementedFingerprintGatewayServer) Analyze(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Analyze not implemented")
}
func (UnimplementedFingerprintGatewayServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedFingerprintGatewayServer) mustEmbedUnimplementedFingerprintGatewayServer() {}
func (UnimplementedFingerprintGatewayServer) testEmbeddedByValue()                            {}

// UnsafeFingerprintGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FingerprintGatewayServer will
// result in compilation errors.
type UnsafeFingerprintGatewayServer interface {
	mustEmbedUnimplementedFingerprintGatewayServer()
}

func RegisterFingerprintGatewayServer(s grpc.ServiceRegistrar, srv FingerprintGatewayServer) {
	// If the following call pancis, it indicates UnimplementedFingerprintGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FingerprintGateway_ServiceDesc, srv)
}

func _FingerprintGateway_Analyze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FingerprintGatewayServer).Analyze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FingerprintGateway_Analyze_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FingerprintGatewayServer).Analyze(ctx, req.(*AnalyzeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FingerprintGateway_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FingerprintGatewayServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FingerprintGateway_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FingerprintGatewayServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FingerprintGateway_ServiceDesc is the grpc.ServiceDesc for FingerprintGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FingerprintGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fingerprint.gateway.v1.FingerprintGateway",
	HandlerType: (*FingerprintGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Analyze",
			Handler:    _FingerprintGateway_Analyze_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _FingerprintGateway_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "modules/gateway/proto/fingerprint/v1/gateway.proto",
}
